/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`nodes_sdn_get_ip_vrf`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesSdnGetIpVrfError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_sdn_get_mac_vrf`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesSdnGetMacVrfError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_sdn_get_sdn`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesSdnGetSdnError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_sdn_get_vnets`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesSdnGetVnetsError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_sdn_get_zones`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesSdnGetZonesError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}


/// Get the IP-VRF for an EVPN zone for a node on a given remote
pub async fn nodes_sdn_get_ip_vrf(configuration: &configuration::Configuration, node: &str, remote: &str, zone: &str) -> Result<models::NodesSdnGetIpVrfResponse, Error<NodesSdnGetIpVrfError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;
    let p_query_remote = remote;
    let p_path_zone = zone;

    let uri_str = format!("{}/nodes/{node}/sdn/zones/{zone}/ip-vrf", configuration.base_path, node=crate::apis::urlencode(p_path_node), zone=crate::apis::urlencode(p_path_zone));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("remote", &p_query_remote.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesSdnGetIpVrfResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesSdnGetIpVrfResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesSdnGetIpVrfError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the MAC-VRF for an EVPN vnet for a node on a given remote
pub async fn nodes_sdn_get_mac_vrf(configuration: &configuration::Configuration, node: &str, remote: &str, vnet: &str) -> Result<models::NodesSdnGetMacVrfResponse, Error<NodesSdnGetMacVrfError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;
    let p_query_remote = remote;
    let p_path_vnet = vnet;

    let uri_str = format!("{}/nodes/{node}/sdn/vnets/{vnet}/mac-vrf", configuration.base_path, node=crate::apis::urlencode(p_path_node), vnet=crate::apis::urlencode(p_path_vnet));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("remote", &p_query_remote.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesSdnGetMacVrfResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesSdnGetMacVrfResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesSdnGetMacVrfError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Directory index.
pub async fn nodes_sdn_get_sdn(configuration: &configuration::Configuration, node: &str) -> Result<models::NodesSdnGetSdnResponse, Error<NodesSdnGetSdnError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;

    let uri_str = format!("{}/nodes/{node}/sdn", configuration.base_path, node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesSdnGetSdnResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesSdnGetSdnResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesSdnGetSdnError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Directory index.
pub async fn nodes_sdn_get_vnets(configuration: &configuration::Configuration, node: &str, vnet: &str) -> Result<models::NodesSdnGetVnetsResponse, Error<NodesSdnGetVnetsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;
    let p_path_vnet = vnet;

    let uri_str = format!("{}/nodes/{node}/sdn/vnets/{vnet}", configuration.base_path, node=crate::apis::urlencode(p_path_node), vnet=crate::apis::urlencode(p_path_vnet));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesSdnGetVnetsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesSdnGetVnetsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesSdnGetVnetsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Directory index.
pub async fn nodes_sdn_get_zones(configuration: &configuration::Configuration, node: &str, zone: &str) -> Result<models::NodesSdnGetZonesResponse, Error<NodesSdnGetZonesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;
    let p_path_zone = zone;

    let uri_str = format!("{}/nodes/{node}/sdn/zones/{zone}", configuration.base_path, node=crate::apis::urlencode(p_path_node), zone=crate::apis::urlencode(p_path_zone));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesSdnGetZonesResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesSdnGetZonesResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesSdnGetZonesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

