/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`nodes_network_create_network`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesNetworkCreateNetworkError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_network_delete_network`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesNetworkDeleteNetworkError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_network_delete_nodes_by_node_network_by_iface`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesNetworkDeleteNodesByNodeNetworkByIfaceError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_network_get_network`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesNetworkGetNetworkError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_network_get_nodes_by_node_network_by_iface`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesNetworkGetNodesByNodeNetworkByIfaceError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_network_update_network`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesNetworkUpdateNetworkError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`nodes_network_update_nodes_by_node_network_by_iface`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum NodesNetworkUpdateNodesByNodeNetworkByIfaceError {
    Status400(models::PdmError),
    Status401(models::PdmError),
    Status403(models::PdmError),
    Status404(models::PdmError),
    Status500(models::PdmError),
    Status501(models::PdmError),
    Status503(models::PdmError),
    UnknownValue(serde_json::Value),
}


/// Create network interface configuration.
pub async fn nodes_network_create_network(configuration: &configuration::Configuration, node: &str, nodes_network_create_network_request: models::NodesNetworkCreateNetworkRequest) -> Result<models::NodesNetworkCreateNetworkResponse, Error<NodesNetworkCreateNetworkError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;
    let p_body_nodes_network_create_network_request = nodes_network_create_network_request;

    let uri_str = format!("{}/nodes/{node}/network", configuration.base_path, node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_nodes_network_create_network_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesNetworkCreateNetworkResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesNetworkCreateNetworkResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesNetworkCreateNetworkError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Revert network configuration (rm /etc/network/interfaces.new).
pub async fn nodes_network_delete_network(configuration: &configuration::Configuration, node: &str) -> Result<models::NodesNetworkDeleteNetworkResponse, Error<NodesNetworkDeleteNetworkError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;

    let uri_str = format!("{}/nodes/{node}/network", configuration.base_path, node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesNetworkDeleteNetworkResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesNetworkDeleteNetworkResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesNetworkDeleteNetworkError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Remove network interface configuration.
pub async fn nodes_network_delete_nodes_by_node_network_by_iface(configuration: &configuration::Configuration, iface: &str, node: &str, digest: Option<&str>) -> Result<models::NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse, Error<NodesNetworkDeleteNodesByNodeNetworkByIfaceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_iface = iface;
    let p_path_node = node;
    let p_query_digest = digest;

    let uri_str = format!("{}/nodes/{node}/network/{iface}", configuration.base_path, iface=crate::apis::urlencode(p_path_iface), node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query_digest {
        req_builder = req_builder.query(&[("digest", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesNetworkDeleteNodesByNodeNetworkByIfaceResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesNetworkDeleteNodesByNodeNetworkByIfaceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List all network devices
pub async fn nodes_network_get_network(configuration: &configuration::Configuration, node: &str) -> Result<models::NodesNetworkGetNetworkResponse, Error<NodesNetworkGetNetworkError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;

    let uri_str = format!("{}/nodes/{node}/network", configuration.base_path, node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesNetworkGetNetworkResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesNetworkGetNetworkResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesNetworkGetNetworkError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Read a network interface configuration.
pub async fn nodes_network_get_nodes_by_node_network_by_iface(configuration: &configuration::Configuration, iface: &str, node: &str) -> Result<models::NodesNetworkGetNodesByNodeNetworkByIfaceResponse, Error<NodesNetworkGetNodesByNodeNetworkByIfaceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_iface = iface;
    let p_path_node = node;

    let uri_str = format!("{}/nodes/{node}/network/{iface}", configuration.base_path, iface=crate::apis::urlencode(p_path_iface), node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesNetworkGetNodesByNodeNetworkByIfaceResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesNetworkGetNodesByNodeNetworkByIfaceResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesNetworkGetNodesByNodeNetworkByIfaceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Reload network configuration (requires ifupdown2).
pub async fn nodes_network_update_network(configuration: &configuration::Configuration, node: &str) -> Result<models::NodesNetworkUpdateNetworkResponse, Error<NodesNetworkUpdateNetworkError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_node = node;

    let uri_str = format!("{}/nodes/{node}/network", configuration.base_path, node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesNetworkUpdateNetworkResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesNetworkUpdateNetworkResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesNetworkUpdateNetworkError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update network interface config.
pub async fn nodes_network_update_nodes_by_node_network_by_iface(configuration: &configuration::Configuration, iface: &str, node: &str, nodes_network_update_nodes_by_node_network_by_iface_request: Option<models::NodesNetworkUpdateNodesByNodeNetworkByIfaceRequest>) -> Result<models::NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse, Error<NodesNetworkUpdateNodesByNodeNetworkByIfaceError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_iface = iface;
    let p_path_node = node;
    let p_body_nodes_network_update_nodes_by_node_network_by_iface_request = nodes_network_update_nodes_by_node_network_by_iface_request;

    let uri_str = format!("{}/nodes/{node}/network/{iface}", configuration.base_path, iface=crate::apis::urlencode(p_path_iface), node=crate::apis::urlencode(p_path_node));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_nodes_network_update_nodes_by_node_network_by_iface_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodesNetworkUpdateNodesByNodeNetworkByIfaceResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<NodesNetworkUpdateNodesByNodeNetworkByIfaceError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

