/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessTfaGetTfaResponseDataInner {

    /// TFA entries.
    #[serde(rename = "entries")]
    pub entries: Vec<models::AccessTfaGetTfaResponseDataInnerEntriesInner>,

    /// If a user's second factor is blocked, this contains the block's expiration time.
    #[serde(rename = "tfa-locked-until", skip_serializing_if = "Option::is_none")]
    pub tfa_locked_until: Option<i64>,

    /// The user is locked out of TOTP authentication.
    #[serde(rename = "totp-locked")]
    pub totp_locked: bool,

    /// The user this entry belongs to.
    #[serde(rename = "userid")]
    pub userid: String,


}

impl AccessTfaGetTfaResponseDataInner {
    pub fn new(entries: Vec<models::AccessTfaGetTfaResponseDataInnerEntriesInner>, totp_locked: bool, userid: String) -> AccessTfaGetTfaResponseDataInner {
        AccessTfaGetTfaResponseDataInner {
            
            entries,
            
            tfa_locked_until: None,
            
            totp_locked,
            
            userid,
            
        }
    }
}


