/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessTfaUpdateTfaRequest {

    /// A description to distinguish multiple entries from one another
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// Whether this entry should currently be enabled or disabled
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,

    /// Password.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,


}

impl AccessTfaUpdateTfaRequest {
    pub fn new() -> AccessTfaUpdateTfaRequest {
        AccessTfaUpdateTfaRequest {
            
            description: None,
            
            enable: None,
            
            password: None,
            
        }
    }
}


