/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessUsersCreateTokenResponseData {

    /// Authentication ID
    #[serde(rename = "tokenid")]
    pub tokenid: String,

    /// The secret associated with the token.
    #[serde(rename = "value")]
    pub value: String,


}

impl AccessUsersCreateTokenResponseData {
    pub fn new(tokenid: String, value: String) -> AccessUsersCreateTokenResponseData {
        AccessUsersCreateTokenResponseData {
            
            tokenid,
            
            value,
            
        }
    }
}


