/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessGetRolesResponseDataInner {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of Privileges
    #[serde(rename = "privs")]
    pub privs: Vec<String>,

    /// The id of the role
    #[serde(rename = "roleid")]
    pub roleid: String,


}

impl AccessGetRolesResponseDataInner {
    pub fn new(privs: Vec<String>, roleid: String) -> AccessGetRolesResponseDataInner {
        AccessGetRolesResponseDataInner {
            
            comment: None,
            
            privs,
            
            roleid,
            
        }
    }
}


