/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessTfaGetTfaResponseDataInnerEntriesInner {

    /// Creation time of this entry as unix epoch.
    #[serde(rename = "created")]
    pub created: i64,

    /// User chosen description for this entry.
    #[serde(rename = "description")]
    pub description: String,

    /// Whether this TFA entry is currently enabled.
    #[serde(rename = "enable")]
    pub enable: bool,

    /// The id used to reference this entry.
    #[serde(rename = "id")]
    pub id: String,

    /// A TFA entry type.
    #[serde(rename = "type")]
    pub r#type: models::PdmTypeEnum,


}

impl AccessTfaGetTfaResponseDataInnerEntriesInner {
    pub fn new(created: i64, description: String, enable: bool, id: String, r#type: models::PdmTypeEnum) -> AccessTfaGetTfaResponseDataInnerEntriesInner {
        AccessTfaGetTfaResponseDataInnerEntriesInner {
            
            created,
            
            description,
            
            enable,
            
            id,
            
            r#type,
            
        }
    }
}


