/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessDomainsCreateSyncRequest {

    /// If set, do not create/delete anything
    #[serde(rename = "dry-run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,

    /// Enable newly synced users immediately
    #[serde(rename = "enable-new", skip_serializing_if = "Option::is_none")]
    pub enable_new: Option<bool>,

    /// A semicolon-separated list of things to remove when they or the user vanishes during user synchronization. The following values are possible: ``entry`` removes the user when not returned from the sync; ``properties`` removes any  properties on existing user that do not appear in the source. ``acl`` removes ACLs when the user is not returned from the sync.
    #[serde(rename = "remove-vanished", skip_serializing_if = "Option::is_none")]
    pub remove_vanished: Option<Box<models::PdmRemoveVanishedField>>,


}

impl AccessDomainsCreateSyncRequest {
    pub fn new() -> AccessDomainsCreateSyncRequest {
        AccessDomainsCreateSyncRequest {
            
            dry_run: None,
            
            enable_new: None,
            
            remove_vanished: None,
            
        }
    }
}


