/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessAclUpdateAclRequest {

    /// Authentication ID
    #[serde(rename = "auth-id", skip_serializing_if = "Option::is_none")]
    pub auth_id: Option<String>,

    /// Remove permissions (instead of adding it).
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Group ID
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,

    /// Access control path.
    #[serde(rename = "path")]
    pub path: String,

    /// Allow to propagate (inherit) permissions.
    #[serde(rename = "propagate", skip_serializing_if = "Option::is_none")]
    pub propagate: Option<bool>,

    /// Name of a role that the auth id will be granted.
    #[serde(rename = "role")]
    pub role: String,


}

impl AccessAclUpdateAclRequest {
    pub fn new(path: String, role: String) -> AccessAclUpdateAclRequest {
        AccessAclUpdateAclRequest {
            
            auth_id: None,
            
            delete: None,
            
            digest: None,
            
            group: None,
            
            path,
            
            propagate: None,
            
            role,
            
        }
    }
}


