/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessUsersCreateUsersRequest {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// E-Mail Address.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,

    /// Enable the account (default). You can set this to '0' to disable the account.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,

    /// Account expiration date (seconds since epoch). '0' means no expiration date.
    #[serde(rename = "expire", skip_serializing_if = "Option::is_none")]
    pub expire: Option<i64>,

    /// First name.
    #[serde(rename = "firstname", skip_serializing_if = "Option::is_none")]
    pub firstname: Option<String>,

    /// Last name.
    #[serde(rename = "lastname", skip_serializing_if = "Option::is_none")]
    pub lastname: Option<String>,

    /// User Password.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,

    /// User ID
    #[serde(rename = "userid")]
    pub userid: String,


}

impl AccessUsersCreateUsersRequest {
    pub fn new(userid: String) -> AccessUsersCreateUsersRequest {
        AccessUsersCreateUsersRequest {
            
            comment: None,
            
            email: None,
            
            enable: None,
            
            expire: None,
            
            firstname: None,
            
            lastname: None,
            
            password: None,
            
            userid,
            
        }
    }
}


