/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessUsersUpdateTokenRequest {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of properties to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<models::PdmAccessUsersInlineEnum2>>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Enable the account (default). You can set this to '0' to disable the account.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,

    /// Account expiration date (seconds since epoch). '0' means no expiration date.
    #[serde(rename = "expire", skip_serializing_if = "Option::is_none")]
    pub expire: Option<i64>,

    /// Regenerate token secret while keeping permissions.
    #[serde(rename = "regenerate", skip_serializing_if = "Option::is_none")]
    pub regenerate: Option<bool>,


}

impl AccessUsersUpdateTokenRequest {
    pub fn new() -> AccessUsersUpdateTokenRequest {
        AccessUsersUpdateTokenRequest {
            
            comment: None,
            
            delete: None,
            
            digest: None,
            
            enable: None,
            
            expire: None,
            
            regenerate: None,
            
        }
    }
}


