/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessUsersGetTokenResponseDataInner {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Enable the account (default). You can set this to '0' to disable the account.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,

    /// Account expiration date (seconds since epoch). '0' means no expiration date.
    #[serde(rename = "expire", skip_serializing_if = "Option::is_none")]
    pub expire: Option<i64>,

    /// The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full `Authid` for such use cases.
    #[serde(rename = "token-name")]
    pub token_name: String,

    /// API Token ID
    #[serde(rename = "tokenid")]
    pub tokenid: String,


}

impl AccessUsersGetTokenResponseDataInner {
    pub fn new(token_name: String, tokenid: String) -> AccessUsersGetTokenResponseDataInner {
        AccessUsersGetTokenResponseDataInner {
            
            comment: None,
            
            enable: None,
            
            expire: None,
            
            token_name,
            
            tokenid,
            
        }
    }
}


