/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessTfaCreateTfaResponseData {

    /// When adding u2f entries, this contains a challenge the user must respond to in order to finish the registration.
    #[serde(rename = "challenge", skip_serializing_if = "Option::is_none")]
    pub challenge: Option<String>,

    /// The id if a newly added TFA entry.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// A list of recovery codes as integers.
    #[serde(rename = "recovery")]
    pub recovery: Vec<i64>,


}

impl AccessTfaCreateTfaResponseData {
    pub fn new(recovery: Vec<i64>) -> AccessTfaCreateTfaResponseData {
        AccessTfaCreateTfaResponseData {
            
            challenge: None,
            
            id: None,
            
            recovery,
            
        }
    }
}


