/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount : ACME Account data. This is the part of the account returned from and possibly sent to the ACME provider. Some fields may be uptdated by the user via a request to the account location, others may not be changed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {

    /// The account's contact info.  This usually contains a `\"mailto:<email address>\"` entry but may also contain some other data if the server accepts it.
    #[serde(rename = "contact")]
    pub contact: Vec<String>,

    #[serde(rename = "externalAccountBinding", skip_serializing_if = "Option::is_none")]
    pub external_account_binding: Option<Box<models::ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding>>,

    /// This is only used by the client when querying an account.
    #[serde(rename = "onlyReturnExisting")]
    pub only_return_existing: bool,

    /// URLs to currently pending orders.
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<String>,

    /// Status of an ACME account.
    #[serde(rename = "status")]
    pub status: models::PdmConfigAcmeStatusEnum,

    /// Indicated whether the user agreed to the ACME provider's terms of service.
    #[serde(rename = "termsOfServiceAgreed", skip_serializing_if = "Option::is_none")]
    pub terms_of_service_agreed: Option<bool>,


}

impl ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {
    /// ACME Account data. This is the part of the account returned from and possibly sent to the ACME provider. Some fields may be uptdated by the user via a request to the account location, others may not be changed.
    pub fn new(contact: Vec<String>, only_return_existing: bool, status: models::PdmConfigAcmeStatusEnum) -> ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {
        ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount {
            
            contact,
            
            external_account_binding: None,
            
            only_return_existing,
            
            orders: None,
            
            status,
            
            terms_of_service_agreed: None,
            
        }
    }
}


