/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigViewsCreateViewsRequest {

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// List of filter rules.
    #[serde(rename = "exclude", skip_serializing_if = "Option::is_none")]
    pub exclude: Option<Vec<String>>,

    /// View name.
    #[serde(rename = "id")]
    pub id: String,

    /// List of filter rules.
    #[serde(rename = "include", skip_serializing_if = "Option::is_none")]
    pub include: Option<Vec<String>>,

    /// Include all resources by default.
    #[serde(rename = "include-all", skip_serializing_if = "Option::is_none")]
    pub include_all: Option<bool>,

    /// The configured layout, encoded as json
    #[serde(rename = "layout", skip_serializing_if = "Option::is_none")]
    pub layout: Option<String>,


}

impl ConfigViewsCreateViewsRequest {
    pub fn new(id: String) -> ConfigViewsCreateViewsRequest {
        ConfigViewsCreateViewsRequest {
            
            digest: None,
            
            exclude: None,
            
            id,
            
            include: None,
            
            include_all: None,
            
            layout: None,
            
        }
    }
}


