/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAccessGetOpenidResponseDataInner {

    /// OpenID ACR List
    #[serde(rename = "acr-values", skip_serializing_if = "Option::is_none")]
    pub acr_values: Option<Box<models::PdmAcrValuesField>>,

    /// Automatically create users if they do not exist.
    #[serde(rename = "autocreate", skip_serializing_if = "Option::is_none")]
    pub autocreate: Option<bool>,

    /// OpenID Client ID
    #[serde(rename = "client-id")]
    pub client_id: String,

    /// OpenID Client Key
    #[serde(rename = "client-key", skip_serializing_if = "Option::is_none")]
    pub client_key: Option<String>,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// True if you want this to be the default realm selected on login.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,

    /// OpenID Issuer Url
    #[serde(rename = "issuer-url")]
    pub issuer_url: String,

    /// OpenID Prompt
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,

    /// Realm name.
    #[serde(rename = "realm")]
    pub realm: String,

    /// OpenID Scope List
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Box<models::PdmScopesField>>,

    /// Use the value of this attribute/claim as unique user name. It is up to the identity provider to guarantee the uniqueness. The OpenID specification only guarantees that Subject ('sub') is unique. Also make sure that the user is not allowed to change that attribute by himself!
    #[serde(rename = "username-claim", skip_serializing_if = "Option::is_none")]
    pub username_claim: Option<String>,


}

impl ConfigAccessGetOpenidResponseDataInner {
    pub fn new(client_id: String, issuer_url: String, realm: String) -> ConfigAccessGetOpenidResponseDataInner {
        ConfigAccessGetOpenidResponseDataInner {
            
            acr_values: None,
            
            autocreate: None,
            
            client_id,
            
            client_key: None,
            
            comment: None,
            
            default: None,
            
            issuer_url,
            
            prompt: None,
            
            realm,
            
            scopes: None,
            
            username_claim: None,
            
        }
    }
}


