/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAcmeUpdateAccountRequest {

    /// List of email addresses.
    #[serde(rename = "contact", skip_serializing_if = "Option::is_none")]
    pub contact: Option<String>,


}

impl ConfigAcmeUpdateAccountRequest {
    pub fn new() -> ConfigAcmeUpdateAccountRequest {
        ConfigAcmeUpdateAccountRequest {
            
            contact: None,
            
        }
    }
}


