/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigCertificateGetCertificateResponseData {

    /// The acme account to use.
    #[serde(rename = "acme", skip_serializing_if = "Option::is_none")]
    pub acme: Option<Box<models::PdmAcmeField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain0", skip_serializing_if = "Option::is_none")]
    pub acmedomain0: Option<Box<models::PdmAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain1", skip_serializing_if = "Option::is_none")]
    pub acmedomain1: Option<Box<models::PdmAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain2", skip_serializing_if = "Option::is_none")]
    pub acmedomain2: Option<Box<models::PdmAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain3", skip_serializing_if = "Option::is_none")]
    pub acmedomain3: Option<Box<models::PdmAcmedomainField>>,

    /// ACME domain configuration string
    #[serde(rename = "acmedomain4", skip_serializing_if = "Option::is_none")]
    pub acmedomain4: Option<Box<models::PdmAcmedomainField>>,


}

impl ConfigCertificateGetCertificateResponseData {
    pub fn new() -> ConfigCertificateGetCertificateResponseData {
        ConfigCertificateGetCertificateResponseData {
            
            acme: None,
            
            acmedomain0: None,
            
            acmedomain1: None,
            
            acmedomain2: None,
            
            acmedomain3: None,
            
            acmedomain4: None,
            
        }
    }
}


