/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAcmeGetPluginsResponseDataInner {

    /// DNS Api name.
    #[serde(rename = "api", skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,

    /// Plugin configuration data.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,

    /// Flag to disable the config.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,

    /// Plugin ID.
    #[serde(rename = "plugin")]
    pub plugin: String,

    /// Plugin type.
    #[serde(rename = "type")]
    pub r#type: String,

    /// Extra delay in seconds to wait before requesting validation.  Allows to cope with long TTL of DNS records.
    #[serde(rename = "validation-delay", skip_serializing_if = "Option::is_none")]
    pub validation_delay: Option<i32>,


}

impl ConfigAcmeGetPluginsResponseDataInner {
    pub fn new(plugin: String, r#type: String) -> ConfigAcmeGetPluginsResponseDataInner {
        ConfigAcmeGetPluginsResponseDataInner {
            
            api: None,
            
            data: None,
            
            disable: None,
            
            plugin,
            
            r#type,
            
            validation_delay: None,
            
        }
    }
}


