/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAccessUpdateAdRequest {

    /// LDAP Domain
    #[serde(rename = "base-dn", skip_serializing_if = "Option::is_none")]
    pub base_dn: Option<String>,

    /// LDAP Domain
    #[serde(rename = "bind-dn", skip_serializing_if = "Option::is_none")]
    pub bind_dn: Option<String>,

    /// CA certificate to use for the server. The path can point to either a file, or a directory. If it points to a file, the PEM-formatted X.509 certificate stored at the path will be added as a trusted certificate. If the path points to a directory, the directory replaces the system's default certificate store at `/etc/ssl/certs` - Every file in the directory will be loaded as a trusted certificate.
    #[serde(rename = "capath", skip_serializing_if = "Option::is_none")]
    pub capath: Option<String>,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// True if you want this to be the default realm selected on login.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,

    /// List of properties to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<models::PdmDeleteEnum>>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Custom LDAP search filter for user sync
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,

    /// LDAP connection type
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::PdmModeEnum>,

    /// AD bind password
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,

    /// AD server Port
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,

    /// AD server address
    #[serde(rename = "server1", skip_serializing_if = "Option::is_none")]
    pub server1: Option<String>,

    /// Fallback AD server address
    #[serde(rename = "server2", skip_serializing_if = "Option::is_none")]
    pub server2: Option<String>,

    /// Comma-separated list of key=value pairs for specifying which LDAP attributes map to which peat user field. For example, to map the LDAP attribute ``mail`` to peat's ``email``, write ``email=mail``.
    #[serde(rename = "sync-attributes", skip_serializing_if = "Option::is_none")]
    pub sync_attributes: Option<Box<models::PdmSyncAttributesField>>,

    /// sync defaults options
    #[serde(rename = "sync-defaults-options", skip_serializing_if = "Option::is_none")]
    pub sync_defaults_options: Option<Box<models::PdmSyncDefaultsOptionsField>>,

    /// Comma-separated list of allowed objectClass values for user synchronization. For instance, if ``user-classes`` is set to ``person,user``, then user synchronization will consider all LDAP entities where ``objectClass: person`` `or` ``objectClass: user``.
    #[serde(rename = "user-classes", skip_serializing_if = "Option::is_none")]
    pub user_classes: Option<Box<models::PdmUserClassesField>>,

    /// Verify server certificate
    #[serde(rename = "verify", skip_serializing_if = "Option::is_none")]
    pub verify: Option<bool>,


}

impl ConfigAccessUpdateAdRequest {
    pub fn new() -> ConfigAccessUpdateAdRequest {
        ConfigAccessUpdateAdRequest {
            
            base_dn: None,
            
            bind_dn: None,
            
            capath: None,
            
            comment: None,
            
            default: None,
            
            delete: None,
            
            digest: None,
            
            filter: None,
            
            mode: None,
            
            password: None,
            
            port: None,
            
            server1: None,
            
            server2: None,
            
            sync_attributes: None,
            
            sync_defaults_options: None,
            
            user_classes: None,
            
            verify: None,
            
        }
    }
}


