/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAcmeGetAccountResponseDataInner {

    /// ACME account name.
    #[serde(rename = "name")]
    pub name: String,


}

impl ConfigAcmeGetAccountResponseDataInner {
    pub fn new(name: String) -> ConfigAcmeGetAccountResponseDataInner {
        ConfigAcmeGetAccountResponseDataInner {
            
            name,
            
        }
    }
}


