/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigAcmeGetConfigAcmeAccountByNameResponseData {

    #[serde(rename = "account")]
    pub account: Box<models::ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount>,

    /// The ACME directory URL the account was created at.
    #[serde(rename = "directory")]
    pub directory: String,

    /// The account's own URL within the ACME directory.
    #[serde(rename = "location")]
    pub location: String,

    /// The ToS URL, if the user agreed to one.
    #[serde(rename = "tos", skip_serializing_if = "Option::is_none")]
    pub tos: Option<String>,


}

impl ConfigAcmeGetConfigAcmeAccountByNameResponseData {
    pub fn new(account: models::ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount, directory: String, location: String) -> ConfigAcmeGetConfigAcmeAccountByNameResponseData {
        ConfigAcmeGetConfigAcmeAccountByNameResponseData {
            
            account: Box::new(account),
            
            directory,
            
            location,
            
            tos: None,
            
        }
    }
}


