/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCertificatesCreateCustomResponseDataInner {

    /// Certificate file name.
    #[serde(rename = "filename")]
    pub filename: String,

    /// The SSL Fingerprint.
    #[serde(rename = "fingerprint", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,

    /// Certificate issuer name.
    #[serde(rename = "issuer")]
    pub issuer: String,

    /// Certificate's notAfter timestamp (UNIX epoch).
    #[serde(rename = "notafter", skip_serializing_if = "Option::is_none")]
    pub notafter: Option<i64>,

    /// Certificate's notBefore timestamp (UNIX epoch).
    #[serde(rename = "notbefore", skip_serializing_if = "Option::is_none")]
    pub notbefore: Option<i64>,

    /// Certificate in PEM format.
    #[serde(rename = "pem", skip_serializing_if = "Option::is_none")]
    pub pem: Option<String>,

    /// Certificate's public key size if available.
    #[serde(rename = "public-key-bits", skip_serializing_if = "Option::is_none")]
    pub public_key_bits: Option<i32>,

    /// Certificate's public key algorithm.
    #[serde(rename = "public-key-type")]
    pub public_key_type: String,

    /// List of certificate's SubjectAlternativeName entries.
    #[serde(rename = "san")]
    pub san: Vec<String>,

    /// Certificate subject name.
    #[serde(rename = "subject")]
    pub subject: String,


}

impl NodesCertificatesCreateCustomResponseDataInner {
    pub fn new(filename: String, issuer: String, public_key_type: String, san: Vec<String>, subject: String) -> NodesCertificatesCreateCustomResponseDataInner {
        NodesCertificatesCreateCustomResponseDataInner {
            
            filename,
            
            fingerprint: None,
            
            issuer,
            
            notafter: None,
            
            notbefore: None,
            
            pem: None,
            
            public_key_bits: None,
            
            public_key_type,
            
            san,
            
            subject,
            
        }
    }
}


