/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptGetRepositoriesResponseDataFilesInner {

    /// The file content, if already parsed.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// The type of format used for an APT repository.
    #[serde(rename = "file-type")]
    pub file_type: models::PdmFileTypeEnum,

    /// The path to the file. If None, `contents` must be set directly.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    /// List of APT repositories.
    #[serde(rename = "repositories")]
    pub repositories: Vec<models::NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner>,


}

impl NodesAptGetRepositoriesResponseDataFilesInner {
    pub fn new(file_type: models::PdmFileTypeEnum, repositories: Vec<models::NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInner>) -> NodesAptGetRepositoriesResponseDataFilesInner {
        NodesAptGetRepositoriesResponseDataFilesInner {
            
            content: None,
            
            digest: None,
            
            file_type,
            
            path: None,
            
            repositories,
            
        }
    }
}


