/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {

    /// Option key.
    #[serde(rename = "Key")]
    pub key: String,

    /// Option values.
    #[serde(rename = "Values")]
    pub values: Vec<String>,


}

impl NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {
    pub fn new(key: String, values: Vec<String>) -> NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {
        NodesAptGetRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {
            
            key,
            
            values,
            
        }
    }
}


