/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptGetRepositoriesResponseDataErrorsInner {

    /// The error message.
    #[serde(rename = "error")]
    pub error: String,

    /// The path to the problematic file.
    #[serde(rename = "path")]
    pub path: String,


}

impl NodesAptGetRepositoriesResponseDataErrorsInner {
    pub fn new(error: String, path: String) -> NodesAptGetRepositoriesResponseDataErrorsInner {
        NodesAptGetRepositoriesResponseDataErrorsInner {
            
            error,
            
            path,
            
        }
    }
}


