/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusGetStatusResponseData {

    #[serde(rename = "boot-info")]
    pub boot_info: Box<models::NodesStatusGetStatusResponseDataBootInfo>,

    /// Total CPU usage since last query.
    #[serde(rename = "cpu")]
    pub cpu: f64,

    #[serde(rename = "cpuinfo")]
    pub cpuinfo: Box<models::NodesStatusGetStatusResponseDataCpuinfo>,

    #[serde(rename = "current-kernel")]
    pub current_kernel: Box<models::NodesStatusGetStatusResponseDataCurrentKernel>,

    #[serde(rename = "info")]
    pub info: Box<models::NodesStatusGetStatusResponseDataInfo>,

    /// The current kernel version (LEGACY string type).
    #[serde(rename = "kversion")]
    pub kversion: String,

    /// Load for 1, 5 and 15 minutes.
    #[serde(rename = "loadavg")]
    pub loadavg: Vec<f64>,

    #[serde(rename = "memory")]
    pub memory: Box<models::NodesStatusGetStatusResponseDataMemory>,

    #[serde(rename = "root")]
    pub root: Box<models::NodesStatusGetStatusResponseDataRoot>,

    #[serde(rename = "swap")]
    pub swap: Box<models::NodesStatusGetStatusResponseDataSwap>,

    /// The current uptime of the server.
    #[serde(rename = "uptime")]
    pub uptime: i64,

    /// Total IO wait since last query.
    #[serde(rename = "wait")]
    pub wait: f64,


}

impl NodesStatusGetStatusResponseData {
    pub fn new(boot_info: models::NodesStatusGetStatusResponseDataBootInfo, cpu: f64, cpuinfo: models::NodesStatusGetStatusResponseDataCpuinfo, current_kernel: models::NodesStatusGetStatusResponseDataCurrentKernel, info: models::NodesStatusGetStatusResponseDataInfo, kversion: String, loadavg: Vec<f64>, memory: models::NodesStatusGetStatusResponseDataMemory, root: models::NodesStatusGetStatusResponseDataRoot, swap: models::NodesStatusGetStatusResponseDataSwap, uptime: i64, wait: f64) -> NodesStatusGetStatusResponseData {
        NodesStatusGetStatusResponseData {
            
            boot_info: Box::new(boot_info),
            
            cpu,
            
            cpuinfo: Box::new(cpuinfo),
            
            current_kernel: Box::new(current_kernel),
            
            info: Box::new(info),
            
            kversion,
            
            loadavg,
            
            memory: Box::new(memory),
            
            root: Box::new(root),
            
            swap: Box::new(swap),
            
            uptime,
            
            wait,
            
        }
    }
}


