/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusCreateStatusRequest {

    /// Node Power command type.
    #[serde(rename = "command")]
    pub command: models::PdmNodesStatusCommandEnum,


}

impl NodesStatusCreateStatusRequest {
    pub fn new(command: models::PdmNodesStatusCommandEnum) -> NodesStatusCreateStatusRequest {
        NodesStatusCreateStatusRequest {
            
            command,
            
        }
    }
}


