/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodesStatusGetStatusResponseDataRoot : Storage space usage information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusGetStatusResponseDataRoot {

    /// Available space (bytes).
    #[serde(rename = "avail")]
    pub avail: i64,

    /// Total space (bytes).
    #[serde(rename = "total")]
    pub total: i64,

    /// Used space (bytes).
    #[serde(rename = "used")]
    pub used: i64,


}

impl NodesStatusGetStatusResponseDataRoot {
    /// Storage space usage information.
    pub fn new(avail: i64, total: i64, used: i64) -> NodesStatusGetStatusResponseDataRoot {
        NodesStatusGetStatusResponseDataRoot {
            
            avail,
            
            total,
            
            used,
            
        }
    }
}


