/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesTasksGetTasksResponseDataInner {

    /// The task end time (Epoch)
    #[serde(rename = "endtime", skip_serializing_if = "Option::is_none")]
    pub endtime: Option<i64>,

    /// The node name where the task is running on.
    #[serde(rename = "node")]
    pub node: String,

    /// The Unix PID
    #[serde(rename = "pid")]
    pub pid: i64,

    /// The task start time (Epoch)
    #[serde(rename = "pstart")]
    pub pstart: i64,

    /// The task start time (Epoch)
    #[serde(rename = "starttime")]
    pub starttime: i64,

    /// Task end status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,

    /// Unique Process/Task Identifier
    #[serde(rename = "upid")]
    pub upid: String,

    /// The authenticated entity who started the task
    #[serde(rename = "user")]
    pub user: String,

    /// Worker ID (arbitrary ASCII string)
    #[serde(rename = "worker_id", skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,

    /// Worker type (arbitrary ASCII string)
    #[serde(rename = "worker_type")]
    pub worker_type: String,


}

impl NodesTasksGetTasksResponseDataInner {
    pub fn new(node: String, pid: i64, pstart: i64, starttime: i64, upid: String, user: String, worker_type: String) -> NodesTasksGetTasksResponseDataInner {
        NodesTasksGetTasksResponseDataInner {
            
            endtime: None,
            
            node,
            
            pid,
            
            pstart,
            
            starttime,
            
            status: None,
            
            upid,
            
            user,
            
            worker_id: None,
            
            worker_type,
            
        }
    }
}


