/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesGetRrdataResponseDataInner {

    /// Timestamp (UNIX epoch)
    #[serde(rename = "time")]
    pub time: i64,

    /// Total time in milliseconds needed for full metric collection run.
    #[serde(rename = "total-time", skip_serializing_if = "Option::is_none")]
    pub total_time: Option<f64>,


}

impl NodesGetRrdataResponseDataInner {
    pub fn new(time: i64) -> NodesGetRrdataResponseDataInner {
        NodesGetRrdataResponseDataInner {
            
            time,
            
            total_time: None,
            
        }
    }
}


