/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodesStatusGetStatusResponseDataMemory : Node memory usage counters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusGetStatusResponseDataMemory {

    /// Free memory
    #[serde(rename = "free")]
    pub free: i64,

    /// Total memory
    #[serde(rename = "total")]
    pub total: i64,

    /// Used memory
    #[serde(rename = "used")]
    pub used: i64,


}

impl NodesStatusGetStatusResponseDataMemory {
    /// Node memory usage counters
    pub fn new(free: i64, total: i64, used: i64) -> NodesStatusGetStatusResponseDataMemory {
        NodesStatusGetStatusResponseDataMemory {
            
            free,
            
            total,
            
            used,
            
        }
    }
}


