/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDnsGetDnsResponseData {

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest")]
    pub digest: String,

    /// First name server IP address.
    #[serde(rename = "dns1", skip_serializing_if = "Option::is_none")]
    pub dns1: Option<String>,

    /// Second name server IP address.
    #[serde(rename = "dns2", skip_serializing_if = "Option::is_none")]
    pub dns2: Option<String>,

    /// Third name server IP address.
    #[serde(rename = "dns3", skip_serializing_if = "Option::is_none")]
    pub dns3: Option<String>,

    /// Other data found in the configuration file (resolv.conf).
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<String>,

    /// Search domain for host-name lookup.
    #[serde(rename = "search", skip_serializing_if = "Option::is_none")]
    pub search: Option<String>,


}

impl NodesDnsGetDnsResponseData {
    pub fn new(digest: String) -> NodesDnsGetDnsResponseData {
        NodesDnsGetDnsResponseData {
            
            digest,
            
            dns1: None,
            
            dns2: None,
            
            dns3: None,
            
            options: None,
            
            search: None,
            
        }
    }
}


