/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCertificatesCreateCustomRequest {

    /// PEM encoded certificate (chain).
    #[serde(rename = "certificates")]
    pub certificates: String,

    /// Force replacement of existing files.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,

    /// PEM encoded private key.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// UI compatibility parameter, ignored
    #[serde(rename = "restart", skip_serializing_if = "Option::is_none")]
    pub restart: Option<bool>,


}

impl NodesCertificatesCreateCustomRequest {
    pub fn new(certificates: String) -> NodesCertificatesCreateCustomRequest {
        NodesCertificatesCreateCustomRequest {
            
            certificates,
            
            force: None,
            
            key: None,
            
            restart: None,
            
        }
    }
}


