/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesSubscriptionGetSubscriptionResponseData {

    /// timestamp of the last check done
    #[serde(rename = "checktime", skip_serializing_if = "Option::is_none")]
    pub checktime: Option<i64>,

    /// the subscription key, if set and permitted to access
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// a more human readable status message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,

    /// next due date of the set subscription
    #[serde(rename = "nextduedate", skip_serializing_if = "Option::is_none")]
    pub nextduedate: Option<String>,

    /// human readable productname of the set subscription
    #[serde(rename = "productname", skip_serializing_if = "Option::is_none")]
    pub productname: Option<String>,

    /// register date of the set subscription
    #[serde(rename = "regdate", skip_serializing_if = "Option::is_none")]
    pub regdate: Option<String>,

    /// the server ID, if permitted to access
    #[serde(rename = "serverid", skip_serializing_if = "Option::is_none")]
    pub serverid: Option<String>,

    /// Signature for offline keys
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,

    /// Subscription status
    #[serde(rename = "status")]
    pub status: models::PdmStatusEnum,

    /// URL to the web shop
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,


}

impl NodesSubscriptionGetSubscriptionResponseData {
    pub fn new(status: models::PdmStatusEnum) -> NodesSubscriptionGetSubscriptionResponseData {
        NodesSubscriptionGetSubscriptionResponseData {
            
            checktime: None,
            
            key: None,
            
            message: None,
            
            nextduedate: None,
            
            productname: None,
            
            regdate: None,
            
            serverid: None,
            
            signature: None,
            
            status,
            
            url: None,
            
        }
    }
}


