/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesTimeGetTimeResponseData {

    /// Seconds since 1970-01-01 00:00:00 UTC. (local time)
    #[serde(rename = "localtime")]
    pub localtime: i64,

    /// Seconds since 1970-01-01 00:00:00 UTC.
    #[serde(rename = "time")]
    pub time: i64,

    /// Time zone. The file '/usr/share/zoneinfo/zone.tab' contains the list of valid names.
    #[serde(rename = "timezone")]
    pub timezone: String,


}

impl NodesTimeGetTimeResponseData {
    pub fn new(localtime: i64, time: i64, timezone: String) -> NodesTimeGetTimeResponseData {
        NodesTimeGetTimeResponseData {
            
            localtime,
            
            time,
            
            timezone,
            
        }
    }
}


