/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptGetRepositoriesResponseData {

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest")]
    pub digest: String,

    /// List of problematic files.
    #[serde(rename = "errors")]
    pub errors: Vec<models::NodesAptGetRepositoriesResponseDataErrorsInner>,

    /// List of parsed repository files.
    #[serde(rename = "files")]
    pub files: Vec<models::NodesAptGetRepositoriesResponseDataFilesInner>,

    /// List of additional information/warnings about the repositories
    #[serde(rename = "infos")]
    pub infos: Vec<models::NodesAptGetRepositoriesResponseDataInfosInner>,

    /// List of standard repositories and their configuration status.
    #[serde(rename = "standard-repos")]
    pub standard_repos: Vec<models::NodesAptGetRepositoriesResponseDataStandardReposInner>,


}

impl NodesAptGetRepositoriesResponseData {
    pub fn new(digest: String, errors: Vec<models::NodesAptGetRepositoriesResponseDataErrorsInner>, files: Vec<models::NodesAptGetRepositoriesResponseDataFilesInner>, infos: Vec<models::NodesAptGetRepositoriesResponseDataInfosInner>, standard_repos: Vec<models::NodesAptGetRepositoriesResponseDataStandardReposInner>) -> NodesAptGetRepositoriesResponseData {
        NodesAptGetRepositoriesResponseData {
            
            digest,
            
            errors,
            
            files,
            
            infos,
            
            standard_repos,
            
        }
    }
}


