/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodesStatusGetStatusResponseDataCpuinfo : Information about the CPU
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusGetStatusResponseDataCpuinfo {

    /// The number of CPU cores (incl. threads)
    #[serde(rename = "cpus")]
    pub cpus: i64,

    /// The CPU model
    #[serde(rename = "model")]
    pub model: String,

    /// The number of CPU sockets
    #[serde(rename = "sockets")]
    pub sockets: i64,


}

impl NodesStatusGetStatusResponseDataCpuinfo {
    /// Information about the CPU
    pub fn new(cpus: i64, model: String, sockets: i64) -> NodesStatusGetStatusResponseDataCpuinfo {
        NodesStatusGetStatusResponseDataCpuinfo {
            
            cpus,
            
            model,
            
            sockets,
            
        }
    }
}


