/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesTasksGetStatusResponseData {

    /// 'OK', 'Error: <msg>', or 'unknown'.
    #[serde(rename = "exitstatus", skip_serializing_if = "Option::is_none")]
    pub exitstatus: Option<String>,

    /// Worker ID (arbitrary ASCII string)
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// Node name (or 'localhost')
    #[serde(rename = "node")]
    pub node: String,

    /// The Unix PID.
    #[serde(rename = "pid")]
    pub pid: i64,

    /// The Unix process start time from `/proc/pid/stat`
    #[serde(rename = "pstart")]
    pub pstart: i64,

    /// The task start time (Epoch)
    #[serde(rename = "starttime")]
    pub starttime: i64,

    /// 'running' or 'stopped'
    #[serde(rename = "status")]
    pub status: String,

    /// The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full `Authid` for such use cases.
    #[serde(rename = "tokenid", skip_serializing_if = "Option::is_none")]
    pub tokenid: Option<String>,

    /// Worker type (arbitrary ASCII string)
    #[serde(rename = "type")]
    pub r#type: String,

    /// Unique Process/Task Identifier
    #[serde(rename = "upid")]
    pub upid: String,

    /// User ID
    #[serde(rename = "user")]
    pub user: String,


}

impl NodesTasksGetStatusResponseData {
    pub fn new(node: String, pid: i64, pstart: i64, starttime: i64, status: String, r#type: String, upid: String, user: String) -> NodesTasksGetStatusResponseData {
        NodesTasksGetStatusResponseData {
            
            exitstatus: None,
            
            id: None,
            
            node,
            
            pid,
            
            pstart,
            
            starttime,
            
            status,
            
            tokenid: None,
            
            r#type,
            
            upid,
            
            user,
            
        }
    }
}


