/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesNetworkGetNetworkResponseDataInner {

    /// Interface is active (UP)
    #[serde(rename = "active")]
    pub active: bool,

    /// List of altnames for this interface
    #[serde(rename = "altnames")]
    pub altnames: Vec<String>,

    /// Autostart interface
    #[serde(rename = "autostart")]
    pub autostart: bool,

    /// Network interface name.
    #[serde(rename = "bond-primary", skip_serializing_if = "Option::is_none")]
    pub bond_primary: Option<String>,

    /// Linux Bond Mode
    #[serde(rename = "bond_mode", skip_serializing_if = "Option::is_none")]
    pub bond_mode: Option<models::PdmBondModeEnum>,

    /// Bond Transmit Hash Policy for LACP (802.3ad)
    #[serde(rename = "bond_xmit_hash_policy", skip_serializing_if = "Option::is_none")]
    pub bond_xmit_hash_policy: Option<models::PdmBondXmitHashPolicyEnum>,

    /// Network interface list.
    #[serde(rename = "bridge_ports", skip_serializing_if = "Option::is_none")]
    pub bridge_ports: Option<Vec<String>>,

    /// Enable bridge vlan support.
    #[serde(rename = "bridge_vlan_aware", skip_serializing_if = "Option::is_none")]
    pub bridge_vlan_aware: Option<bool>,

    /// IPv4 address with netmask (CIDR notation).
    #[serde(rename = "cidr", skip_serializing_if = "Option::is_none")]
    pub cidr: Option<String>,

    /// IPv6 address with netmask (CIDR notation).
    #[serde(rename = "cidr6", skip_serializing_if = "Option::is_none")]
    pub cidr6: Option<String>,

    /// Comments (inet, may span multiple lines)
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<String>,

    /// Comments (inet6, may span multiple lines)
    #[serde(rename = "comments6", skip_serializing_if = "Option::is_none")]
    pub comments6: Option<String>,

    /// IPv4 address.
    #[serde(rename = "gateway", skip_serializing_if = "Option::is_none")]
    pub gateway: Option<String>,

    /// IPv6 address.
    #[serde(rename = "gateway6", skip_serializing_if = "Option::is_none")]
    pub gateway6: Option<String>,

    /// Interface configuration method
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<models::PdmMethodEnum>,

    /// Interface configuration method
    #[serde(rename = "method6", skip_serializing_if = "Option::is_none")]
    pub method6: Option<models::PdmMethodEnum>,

    /// Maximum Transmission Unit
    #[serde(rename = "mtu", skip_serializing_if = "Option::is_none")]
    pub mtu: Option<i64>,

    /// Network interface name.
    #[serde(rename = "name")]
    pub name: String,

    /// Option list (inet)
    #[serde(rename = "options")]
    pub options: Vec<String>,

    /// Option list (inet6)
    #[serde(rename = "options6")]
    pub options6: Vec<String>,

    /// Network interface list.
    #[serde(rename = "slaves", skip_serializing_if = "Option::is_none")]
    pub slaves: Option<Vec<String>>,

    /// Network interface type
    #[serde(rename = "type")]
    pub r#type: models::PdmNodesNetworkTypeEnum,

    /// VLAN ID.
    #[serde(rename = "vlan-id", skip_serializing_if = "Option::is_none")]
    pub vlan_id: Option<i64>,

    /// Network interface name.
    #[serde(rename = "vlan-raw-device", skip_serializing_if = "Option::is_none")]
    pub vlan_raw_device: Option<String>,


}

impl NodesNetworkGetNetworkResponseDataInner {
    pub fn new(active: bool, altnames: Vec<String>, autostart: bool, name: String, options: Vec<String>, options6: Vec<String>, r#type: models::PdmNodesNetworkTypeEnum) -> NodesNetworkGetNetworkResponseDataInner {
        NodesNetworkGetNetworkResponseDataInner {
            
            active,
            
            altnames,
            
            autostart,
            
            bond_primary: None,
            
            bond_mode: None,
            
            bond_xmit_hash_policy: None,
            
            bridge_ports: None,
            
            bridge_vlan_aware: None,
            
            cidr: None,
            
            cidr6: None,
            
            comments: None,
            
            comments6: None,
            
            gateway: None,
            
            gateway6: None,
            
            method: None,
            
            method6: None,
            
            mtu: None,
            
            name,
            
            options,
            
            options6,
            
            slaves: None,
            
            r#type,
            
            vlan_id: None,
            
            vlan_raw_device: None,
            
        }
    }
}


