/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesConfigGetConfigResponseData {

    /// OpenSSL cipher list used by the api server for TLS <= 1.2
    #[serde(rename = "ciphers-tls-1.2", skip_serializing_if = "Option::is_none")]
    pub ciphers_tls_1_2: Option<String>,

    /// OpenSSL ciphersuites list used by the api server for TLS 1.3
    #[serde(rename = "ciphers-tls-1.3", skip_serializing_if = "Option::is_none")]
    pub ciphers_tls_1_3: Option<String>,

    /// All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.
    #[serde(rename = "default-lang", skip_serializing_if = "Option::is_none")]
    pub default_lang: Option<models::PdmDefaultLangEnum>,

    /// E-Mail Address.
    #[serde(rename = "email-from", skip_serializing_if = "Option::is_none")]
    pub email_from: Option<String>,

    /// HTTP proxy configuration [http://]<host>[:port]
    #[serde(rename = "http-proxy", skip_serializing_if = "Option::is_none")]
    pub http_proxy: Option<String>,


}

impl NodesConfigGetConfigResponseData {
    pub fn new() -> NodesConfigGetConfigResponseData {
        NodesConfigGetConfigResponseData {
            
            ciphers_tls_1_2: None,
            
            ciphers_tls_1_3: None,
            
            default_lang: None,
            
            email_from: None,
            
            http_proxy: None,
            
        }
    }
}


