/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodesStatusGetStatusResponseDataBootInfo : Holds the Bootmodes
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusGetStatusResponseDataBootInfo {

    /// The possible BootModes
    #[serde(rename = "mode")]
    pub mode: models::PdmNodesStatusModeEnum,

    /// SecureBoot status
    #[serde(rename = "secureboot")]
    pub secureboot: bool,


}

impl NodesStatusGetStatusResponseDataBootInfo {
    /// Holds the Bootmodes
    pub fn new(mode: models::PdmNodesStatusModeEnum, secureboot: bool) -> NodesStatusGetStatusResponseDataBootInfo {
        NodesStatusGetStatusResponseDataBootInfo {
            
            mode,
            
            secureboot,
            
        }
    }
}


