/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodesTasksGetLogResponseDataData : A line of a task log.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesTasksGetLogResponseDataData {

    /// Line number.
    #[serde(rename = "n")]
    pub n: i64,

    /// The line of the log.
    #[serde(rename = "t")]
    pub t: String,


}

impl NodesTasksGetLogResponseDataData {
    /// A line of a task log.
    pub fn new(n: i64, t: String) -> NodesTasksGetLogResponseDataData {
        NodesTasksGetLogResponseDataData {
            
            n,
            
            t,
            
        }
    }
}


