/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptCreateRepositoriesRequest {

    /// Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Whether the repository should be enabled or not.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,

    /// Index within the file (starting from 0).
    #[serde(rename = "index")]
    pub index: i64,

    /// Path to the containing file.
    #[serde(rename = "path")]
    pub path: String,


}

impl NodesAptCreateRepositoriesRequest {
    pub fn new(index: i64, path: String) -> NodesAptCreateRepositoriesRequest {
        NodesAptCreateRepositoriesRequest {
            
            digest: None,
            
            enabled: None,
            
            index,
            
            path,
            
        }
    }
}


