/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCreateTermproxyResponseData {

    #[serde(rename = "port")]
    pub port: String,

    #[serde(rename = "ticket")]
    pub ticket: String,

    #[serde(rename = "upid")]
    pub upid: String,

    #[serde(rename = "user")]
    pub user: String,


}

impl NodesCreateTermproxyResponseData {
    pub fn new(port: String, ticket: String, upid: String, user: String) -> NodesCreateTermproxyResponseData {
        NodesCreateTermproxyResponseData {
            
            port,
            
            ticket,
            
            upid,
            
            user,
            
        }
    }
}


