/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbsRemotesGetPbsRemotesByRemoteRrddataResponseDataInner {

    /// CPU utilization, averaged over the last minute
    #[serde(rename = "cpu-avg1", skip_serializing_if = "Option::is_none")]
    pub cpu_avg1: Option<f64>,

    /// CPU utilization, averaged over the last fifteen minutes
    #[serde(rename = "cpu-avg15", skip_serializing_if = "Option::is_none")]
    pub cpu_avg15: Option<f64>,

    /// CPU utilization, averaged over the last five minutes
    #[serde(rename = "cpu-avg5", skip_serializing_if = "Option::is_none")]
    pub cpu_avg5: Option<f64>,

    /// Current CPU utilization
    #[serde(rename = "cpu-current", skip_serializing_if = "Option::is_none")]
    pub cpu_current: Option<f64>,

    /// Current IO wait
    #[serde(rename = "cpu-iowait", skip_serializing_if = "Option::is_none")]
    pub cpu_iowait: Option<f64>,

    /// Available disk space
    #[serde(rename = "disk-available", skip_serializing_if = "Option::is_none")]
    pub disk_available: Option<f64>,

    /// Disk read rate
    #[serde(rename = "disk-read", skip_serializing_if = "Option::is_none")]
    pub disk_read: Option<f64>,

    /// Total disk size
    #[serde(rename = "disk-total", skip_serializing_if = "Option::is_none")]
    pub disk_total: Option<f64>,

    /// Disk utiliziation
    #[serde(rename = "disk-used", skip_serializing_if = "Option::is_none")]
    pub disk_used: Option<f64>,

    /// Disk write rate
    #[serde(rename = "disk-write", skip_serializing_if = "Option::is_none")]
    pub disk_write: Option<f64>,

    /// Total memory size
    #[serde(rename = "mem-total", skip_serializing_if = "Option::is_none")]
    pub mem_total: Option<f64>,

    /// Currently used memory
    #[serde(rename = "mem-used", skip_serializing_if = "Option::is_none")]
    pub mem_used: Option<f64>,

    /// Inbound network data rate
    #[serde(rename = "net-in", skip_serializing_if = "Option::is_none")]
    pub net_in: Option<f64>,

    /// Outboud network data rate
    #[serde(rename = "net-out", skip_serializing_if = "Option::is_none")]
    pub net_out: Option<f64>,

    /// Total swap size
    #[serde(rename = "swap-total", skip_serializing_if = "Option::is_none")]
    pub swap_total: Option<f64>,

    /// Currently used swap
    #[serde(rename = "swap-used", skip_serializing_if = "Option::is_none")]
    pub swap_used: Option<f64>,

    /// Timestamp (UNIX epoch)
    #[serde(rename = "time")]
    pub time: i64,


}

impl PbsRemotesGetPbsRemotesByRemoteRrddataResponseDataInner {
    pub fn new(time: i64) -> PbsRemotesGetPbsRemotesByRemoteRrddataResponseDataInner {
        PbsRemotesGetPbsRemotesByRemoteRrddataResponseDataInner {
            
            cpu_avg1: None,
            
            cpu_avg15: None,
            
            cpu_avg5: None,
            
            cpu_current: None,
            
            cpu_iowait: None,
            
            disk_available: None,
            
            disk_read: None,
            
            disk_total: None,
            
            disk_used: None,
            
            disk_write: None,
            
            mem_total: None,
            
            mem_used: None,
            
            net_in: None,
            
            net_out: None,
            
            swap_total: None,
            
            swap_used: None,
            
            time,
            
        }
    }
}


