/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbsCreateScanRequest {

    /// Authentication ID
    #[serde(rename = "authid")]
    pub authid: String,

    /// Fingerprint of the target remote.
    #[serde(rename = "fingerprint", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,

    /// Hostname (with optional port) of the target remote
    #[serde(rename = "hostname")]
    pub hostname: String,

    /// The token secret or the user password.
    #[serde(rename = "token")]
    pub token: String,


}

impl PbsCreateScanRequest {
    pub fn new(authid: String, hostname: String, token: String) -> PbsCreateScanRequest {
        PbsCreateScanRequest {
            
            authid,
            
            fingerprint: None,
            
            hostname,
            
            token,
            
        }
    }
}


