/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PbsRemotesGetSnapshotsResponseDataInnerVerification : Task properties.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbsRemotesGetSnapshotsResponseDataInnerVerification {

    /// Result of a verify operation.
    #[serde(rename = "state")]
    pub state: models::PdmPbsRemotesStateEnum,

    /// Unique Process/Task Identifier
    #[serde(rename = "upid")]
    pub upid: String,


}

impl PbsRemotesGetSnapshotsResponseDataInnerVerification {
    /// Task properties.
    pub fn new(state: models::PdmPbsRemotesStateEnum, upid: String) -> PbsRemotesGetSnapshotsResponseDataInnerVerification {
        PbsRemotesGetSnapshotsResponseDataInnerVerification {
            
            state,
            
            upid,
            
        }
    }
}


