/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {

    /// Exit status, if available.
    #[serde(rename = "exitstatus", skip_serializing_if = "Option::is_none")]
    pub exitstatus: Option<String>,

    /// Task id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// Node the task is running on.
    #[serde(rename = "node")]
    pub node: String,

    /// The Unix PID
    #[serde(rename = "pid")]
    pub pid: i64,

    /// The task start time (Epoch)
    #[serde(rename = "pstart")]
    pub pstart: i64,

    /// The task's start time.
    #[serde(rename = "starttime")]
    pub starttime: i64,

    /// Whether a task is still running.
    #[serde(rename = "status")]
    pub status: models::PdmPbsRemotesStatusEnum,

    /// The task type.
    #[serde(rename = "type")]
    pub r#type: String,

    /// The task's UPID.
    #[serde(rename = "upid")]
    pub upid: String,

    /// The authenticated entity who started the task.
    #[serde(rename = "user")]
    pub user: String,


}

impl PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {
    pub fn new(node: String, pid: i64, pstart: i64, starttime: i64, status: models::PdmPbsRemotesStatusEnum, r#type: String, upid: String, user: String) -> PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {
        PbsRemotesGetPbsRemotesByRemoteTasksByUpidStatusResponseData {
            
            exitstatus: None,
            
            id: None,
            
            node,
            
            pid,
            
            pstart,
            
            starttime,
            
            status,
            
            r#type,
            
            upid,
            
            user,
            
        }
    }
}


