/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbsRemotesGetNamespacesResponseDataInner {

    /// The first line from the namespace's \"notes\"
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Namespace.
    #[serde(rename = "ns")]
    pub ns: String,


}

impl PbsRemotesGetNamespacesResponseDataInner {
    pub fn new(ns: String) -> PbsRemotesGetNamespacesResponseDataInner {
        PbsRemotesGetNamespacesResponseDataInner {
            
            comment: None,
            
            ns,
            
        }
    }
}


