/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PbsRemotesGetRrddataResponseDataInner {

    /// Available disk space
    #[serde(rename = "disk-available", skip_serializing_if = "Option::is_none")]
    pub disk_available: Option<f64>,

    /// Disk read rate
    #[serde(rename = "disk-read", skip_serializing_if = "Option::is_none")]
    pub disk_read: Option<f64>,

    /// Total disk size
    #[serde(rename = "disk-total", skip_serializing_if = "Option::is_none")]
    pub disk_total: Option<f64>,

    /// Disk utiliziation
    #[serde(rename = "disk-used", skip_serializing_if = "Option::is_none")]
    pub disk_used: Option<f64>,

    /// Disk write rate
    #[serde(rename = "disk-write", skip_serializing_if = "Option::is_none")]
    pub disk_write: Option<f64>,

    /// Timestamp (UNIX epoch)
    #[serde(rename = "time")]
    pub time: i64,


}

impl PbsRemotesGetRrddataResponseDataInner {
    pub fn new(time: i64) -> PbsRemotesGetRrddataResponseDataInner {
        PbsRemotesGetRrddataResponseDataInner {
            
            disk_available: None,
            
            disk_read: None,
            
            disk_total: None,
            
            disk_used: None,
            
            disk_write: None,
            
            time,
            
        }
    }
}


