/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmRemotesRemoteConsoleEnum {
    #[serde(rename = "applet")]
    Applet,
    #[serde(rename = "vv")]
    Vv,
    #[serde(rename = "html5")]
    Html5,
    #[serde(rename = "xtermjs")]
    Xtermjs,

}

impl std::fmt::Display for PdmRemotesRemoteConsoleEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Applet => write!(f, "applet"),
            Self::Vv => write!(f, "vv"),
            Self::Html5 => write!(f, "html5"),
            Self::Xtermjs => write!(f, "xtermjs"),
        }
    }
}

impl Default for PdmRemotesRemoteConsoleEnum {
    fn default() -> PdmRemotesRemoteConsoleEnum {
        Self::Applet
    }
}

