/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmNodesCmdEnum {
    #[serde(rename = "login")]
    Login,
    #[serde(rename = "upgrade")]
    Upgrade,

}

impl std::fmt::Display for PdmNodesCmdEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Login => write!(f, "login"),
            Self::Upgrade => write!(f, "upgrade"),
        }
    }
}

impl Default for PdmNodesCmdEnum {
    fn default() -> PdmNodesCmdEnum {
        Self::Login
    }
}

