/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmPveRemotesCmodeEnum {
    #[serde(rename = "shell")]
    Shell,
    #[serde(rename = "console")]
    Console,
    #[serde(rename = "tty")]
    Tty,

}

impl std::fmt::Display for PdmPveRemotesCmodeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Shell => write!(f, "shell"),
            Self::Console => write!(f, "console"),
            Self::Tty => write!(f, "tty"),
        }
    }
}

impl Default for PdmPveRemotesCmodeEnum {
    fn default() -> PdmPveRemotesCmodeEnum {
        Self::Shell
    }
}

