/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmAccessUsersInlineEnum {
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "enable")]
    Enable,
    #[serde(rename = "expire")]
    Expire,
    #[serde(rename = "firstname")]
    Firstname,
    #[serde(rename = "lastname")]
    Lastname,
    #[serde(rename = "email")]
    Email,

}

impl std::fmt::Display for PdmAccessUsersInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Comment => write!(f, "comment"),
            Self::Enable => write!(f, "enable"),
            Self::Expire => write!(f, "expire"),
            Self::Firstname => write!(f, "firstname"),
            Self::Lastname => write!(f, "lastname"),
            Self::Email => write!(f, "email"),
        }
    }
}

impl Default for PdmAccessUsersInlineEnum {
    fn default() -> PdmAccessUsersInlineEnum {
        Self::Comment
    }
}

