/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmDeleteEnum {
    #[serde(rename = "server2")]
    Server2,
    #[serde(rename = "port")]
    Port,
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "verify")]
    Verify,
    #[serde(rename = "mode")]
    Mode,
    #[serde(rename = "bind-dn")]
    BindDn,
    #[serde(rename = "password")]
    Password,
    #[serde(rename = "filter")]
    Filter,
    #[serde(rename = "sync-defaults-options")]
    SyncDefaultsOptions,
    #[serde(rename = "sync-attributes")]
    SyncAttributes,
    #[serde(rename = "user-classes")]
    UserClasses,

}

impl std::fmt::Display for PdmDeleteEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Server2 => write!(f, "server2"),
            Self::Port => write!(f, "port"),
            Self::Comment => write!(f, "comment"),
            Self::Default => write!(f, "default"),
            Self::Verify => write!(f, "verify"),
            Self::Mode => write!(f, "mode"),
            Self::BindDn => write!(f, "bind-dn"),
            Self::Password => write!(f, "password"),
            Self::Filter => write!(f, "filter"),
            Self::SyncDefaultsOptions => write!(f, "sync-defaults-options"),
            Self::SyncAttributes => write!(f, "sync-attributes"),
            Self::UserClasses => write!(f, "user-classes"),
        }
    }
}

impl Default for PdmDeleteEnum {
    fn default() -> PdmDeleteEnum {
        Self::Server2
    }
}

