/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmPbsTypeEnum {
    #[serde(rename = "pve")]
    Pve,
    #[serde(rename = "pbs")]
    Pbs,

}

impl std::fmt::Display for PdmPbsTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pve => write!(f, "pve"),
            Self::Pbs => write!(f, "pbs"),
        }
    }
}

impl Default for PdmPbsTypeEnum {
    fn default() -> PdmPbsTypeEnum {
        Self::Pve
    }
}

