/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmPveRemotesMethodEnum {
    #[serde(rename = "loopback")]
    Loopback,
    #[serde(rename = "dhcp")]
    Dhcp,
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "auto")]
    Auto,

}

impl std::fmt::Display for PdmPveRemotesMethodEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Loopback => write!(f, "loopback"),
            Self::Dhcp => write!(f, "dhcp"),
            Self::Manual => write!(f, "manual"),
            Self::Static => write!(f, "static"),
            Self::Auto => write!(f, "auto"),
        }
    }
}

impl Default for PdmPveRemotesMethodEnum {
    fn default() -> PdmPveRemotesMethodEnum {
        Self::Loopback
    }
}

