/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmAccessAclUgidTypeEnum {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "group")]
    Group,

}

impl std::fmt::Display for PdmAccessAclUgidTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::User => write!(f, "user"),
            Self::Group => write!(f, "group"),
        }
    }
}

impl Default for PdmAccessAclUgidTypeEnum {
    fn default() -> PdmAccessAclUgidTypeEnum {
        Self::User
    }
}

