/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmNodesAptHandleEnum {
    #[serde(rename = "enterprise")]
    Enterprise,
    #[serde(rename = "no-subscription")]
    NoSubscription,
    #[serde(rename = "test")]
    Test,
    #[serde(rename = "ceph-squid-enterprise")]
    CephSquidEnterprise,
    #[serde(rename = "ceph-squid-no-subscription")]
    CephSquidNoSubscription,
    #[serde(rename = "ceph-squid-test")]
    CephSquidTest,

}

impl std::fmt::Display for PdmNodesAptHandleEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enterprise => write!(f, "enterprise"),
            Self::NoSubscription => write!(f, "no-subscription"),
            Self::Test => write!(f, "test"),
            Self::CephSquidEnterprise => write!(f, "ceph-squid-enterprise"),
            Self::CephSquidNoSubscription => write!(f, "ceph-squid-no-subscription"),
            Self::CephSquidTest => write!(f, "ceph-squid-test"),
        }
    }
}

impl Default for PdmNodesAptHandleEnum {
    fn default() -> PdmNodesAptHandleEnum {
        Self::Enterprise
    }
}

