/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmBondXmitHashPolicyEnum {
    #[serde(rename = "layer2")]
    Layer2,
    #[serde(rename = "layer2+3")]
    Layer2Plus3,
    #[serde(rename = "layer3+4")]
    Layer3Plus4,

}

impl std::fmt::Display for PdmBondXmitHashPolicyEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Layer2 => write!(f, "layer2"),
            Self::Layer2Plus3 => write!(f, "layer2+3"),
            Self::Layer3Plus4 => write!(f, "layer3+4"),
        }
    }
}

impl Default for PdmBondXmitHashPolicyEnum {
    fn default() -> PdmBondXmitHashPolicyEnum {
        Self::Layer2
    }
}

