/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmResourcesResourceTypeEnum {
    #[serde(rename = "storage")]
    Storage,
    #[serde(rename = "qemu")]
    Qemu,
    #[serde(rename = "lxc")]
    Lxc,
    #[serde(rename = "network")]
    Network,
    #[serde(rename = "datastore")]
    Datastore,
    #[serde(rename = "node")]
    Node,

}

impl std::fmt::Display for PdmResourcesResourceTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Storage => write!(f, "storage"),
            Self::Qemu => write!(f, "qemu"),
            Self::Lxc => write!(f, "lxc"),
            Self::Network => write!(f, "network"),
            Self::Datastore => write!(f, "datastore"),
            Self::Node => write!(f, "node"),
        }
    }
}

impl Default for PdmResourcesResourceTypeEnum {
    fn default() -> PdmResourcesResourceTypeEnum {
        Self::Storage
    }
}

