/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmAccessDomainsTypeEnum {
    #[serde(rename = "pam")]
    Pam,
    #[serde(rename = "pdm")]
    Pdm,
    #[serde(rename = "openid")]
    Openid,
    #[serde(rename = "ad")]
    Ad,
    #[serde(rename = "ldap")]
    Ldap,

}

impl std::fmt::Display for PdmAccessDomainsTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pam => write!(f, "pam"),
            Self::Pdm => write!(f, "pdm"),
            Self::Openid => write!(f, "openid"),
            Self::Ad => write!(f, "ad"),
            Self::Ldap => write!(f, "ldap"),
        }
    }
}

impl Default for PdmAccessDomainsTypeEnum {
    fn default() -> PdmAccessDomainsTypeEnum {
        Self::Pam
    }
}

