/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdmCdromConfig {

    #[serde(rename = "additionalProperties", deserialize_with = "Option::deserialize")]
    pub additional_properties: Option<serde_json::Value>,

    #[serde(rename = "default_key", deserialize_with = "Option::deserialize")]
    pub default_key: Option<serde_json::Value>,

    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<serde_json::Value>,

    #[serde(rename = "properties")]
    pub properties: Box<models::PdmPropertiesField>,

    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,


}

impl PdmCdromConfig {
    pub fn new(additional_properties: Option<serde_json::Value>, default_key: Option<serde_json::Value>, description: Option<serde_json::Value>, properties: models::PdmPropertiesField, r#type: Option<serde_json::Value>) -> PdmCdromConfig {
        PdmCdromConfig {
            
            additional_properties,
            
            default_key,
            
            description,
            
            properties: Box::new(properties),
            
            r#type,
            
        }
    }
}


