/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmConfigAcmeInlineEnum {
    #[serde(rename = "disable")]
    Disable,
    #[serde(rename = "validation-delay")]
    ValidationDelay,

}

impl std::fmt::Display for PdmConfigAcmeInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Disable => write!(f, "disable"),
            Self::ValidationDelay => write!(f, "validation-delay"),
        }
    }
}

impl Default for PdmConfigAcmeInlineEnum {
    fn default() -> PdmConfigAcmeInlineEnum {
        Self::Disable
    }
}

