/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmPveTfaEnum {
    #[serde(rename = "yubico")]
    Yubico,
    #[serde(rename = "oath")]
    Oath,

}

impl std::fmt::Display for PdmPveTfaEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Yubico => write!(f, "yubico"),
            Self::Oath => write!(f, "oath"),
        }
    }
}

impl Default for PdmPveTfaEnum {
    fn default() -> PdmPveTfaEnum {
        Self::Yubico
    }
}

