/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdmPropertiesConfig {

    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<serde_json::Value>,

    #[serde(rename = "enum", deserialize_with = "Option::deserialize")]
    pub r#enum: Option<serde_json::Value>,

    #[serde(rename = "optional", deserialize_with = "Option::deserialize")]
    pub optional: Option<serde_json::Value>,

    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,


}

impl PdmPropertiesConfig {
    pub fn new(description: Option<serde_json::Value>, r#enum: Option<serde_json::Value>, optional: Option<serde_json::Value>, r#type: Option<serde_json::Value>) -> PdmPropertiesConfig {
        PdmPropertiesConfig {
            
            description,
            
            r#enum,
            
            optional,
            
            r#type,
            
        }
    }
}


