/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmNodesConfigInlineEnum {
    #[serde(rename = "http-proxy")]
    HttpProxy,
    #[serde(rename = "email-from")]
    EmailFrom,
    #[serde(rename = "ciphers-tls-1.3")]
    CiphersTls13,
    #[serde(rename = "ciphers-tls-1.2")]
    CiphersTls12,
    #[serde(rename = "default-lang")]
    DefaultLang,

}

impl std::fmt::Display for PdmNodesConfigInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::HttpProxy => write!(f, "http-proxy"),
            Self::EmailFrom => write!(f, "email-from"),
            Self::CiphersTls13 => write!(f, "ciphers-tls-1.3"),
            Self::CiphersTls12 => write!(f, "ciphers-tls-1.2"),
            Self::DefaultLang => write!(f, "default-lang"),
        }
    }
}

impl Default for PdmNodesConfigInlineEnum {
    fn default() -> PdmNodesConfigInlineEnum {
        Self::HttpProxy
    }
}

