/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PdmCpuField {
    PdmLogRatelimitConfig(Box<models::PdmLogRatelimitConfig>),
    String(String),
}

impl Default for PdmCpuField {
    fn default() -> Self {
        Self::PdmLogRatelimitConfig(Default::default())
    }
}

