/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmVlanProtocolEnum {
    #[serde(rename = "802.1ad")]
    Variant8021ad,
    #[serde(rename = "802.1q")]
    Variant8021q,

}

impl std::fmt::Display for PdmVlanProtocolEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant8021ad => write!(f, "802.1ad"),
            Self::Variant8021q => write!(f, "802.1q"),
        }
    }
}

impl Default for PdmVlanProtocolEnum {
    fn default() -> PdmVlanProtocolEnum {
        Self::Variant8021ad
    }
}

