/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmSdnStateEnum {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "deleted")]
    Deleted,
    #[serde(rename = "changed")]
    Changed,

}

impl std::fmt::Display for PdmSdnStateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::New => write!(f, "new"),
            Self::Deleted => write!(f, "deleted"),
            Self::Changed => write!(f, "changed"),
        }
    }
}

impl Default for PdmSdnStateEnum {
    fn default() -> PdmSdnStateEnum {
        Self::New
    }
}

