/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdmBridgePortsConfig {

    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<serde_json::Value>,

    /// Network interface name.
    #[serde(rename = "items")]
    pub items: String,

    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,


}

impl PdmBridgePortsConfig {
    pub fn new(description: Option<serde_json::Value>, items: String, r#type: Option<serde_json::Value>) -> PdmBridgePortsConfig {
        PdmBridgePortsConfig {
            
            description,
            
            items,
            
            r#type,
            
        }
    }
}


