/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdmNetConfig {

    #[serde(rename = "additionalProperties", deserialize_with = "Option::deserialize")]
    pub additional_properties: Option<serde_json::Value>,

    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<serde_json::Value>,

    #[serde(rename = "properties", deserialize_with = "Option::deserialize")]
    pub properties: Option<serde_json::Value>,

    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,


}

impl PdmNetConfig {
    pub fn new(additional_properties: Option<serde_json::Value>, description: Option<serde_json::Value>, properties: Option<serde_json::Value>, r#type: Option<serde_json::Value>) -> PdmNetConfig {
        PdmNetConfig {
            
            additional_properties,
            
            description,
            
            properties,
            
            r#type,
            
        }
    }
}


