/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmAccessDomainsItemsEnum {
    #[serde(rename = "acl")]
    Acl,
    #[serde(rename = "entry")]
    Entry,
    #[serde(rename = "properties")]
    Properties,

}

impl std::fmt::Display for PdmAccessDomainsItemsEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Acl => write!(f, "acl"),
            Self::Entry => write!(f, "entry"),
            Self::Properties => write!(f, "properties"),
        }
    }
}

impl Default for PdmAccessDomainsItemsEnum {
    fn default() -> PdmAccessDomainsItemsEnum {
        Self::Acl
    }
}

