/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmConfigViewsInlineEnum {
    #[serde(rename = "include")]
    Include,
    #[serde(rename = "exclude")]
    Exclude,
    #[serde(rename = "layout")]
    Layout,
    #[serde(rename = "include-all")]
    IncludeAll,

}

impl std::fmt::Display for PdmConfigViewsInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Include => write!(f, "include"),
            Self::Exclude => write!(f, "exclude"),
            Self::Layout => write!(f, "layout"),
            Self::IncludeAll => write!(f, "include-all"),
        }
    }
}

impl Default for PdmConfigViewsInlineEnum {
    fn default() -> PdmConfigViewsInlineEnum {
        Self::Include
    }
}

