/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmDefaultLangEnum {
    #[serde(rename = "ar")]
    Ar,
    #[serde(rename = "ca")]
    Ca,
    #[serde(rename = "da")]
    Da,
    #[serde(rename = "de")]
    De,
    #[serde(rename = "en")]
    En,
    #[serde(rename = "es")]
    Es,
    #[serde(rename = "eu")]
    Eu,
    #[serde(rename = "fa")]
    Fa,
    #[serde(rename = "fr")]
    Fr,
    #[serde(rename = "gl")]
    Gl,
    #[serde(rename = "he")]
    He,
    #[serde(rename = "hu")]
    Hu,
    #[serde(rename = "it")]
    It,
    #[serde(rename = "ja")]
    Ja,
    #[serde(rename = "kr")]
    Kr,
    #[serde(rename = "nb")]
    Nb,
    #[serde(rename = "nl")]
    Nl,
    #[serde(rename = "nn")]
    Nn,
    #[serde(rename = "pl")]
    Pl,
    #[serde(rename = "pt_BR")]
    PtBr,
    #[serde(rename = "ru")]
    Ru,
    #[serde(rename = "sl")]
    Sl,
    #[serde(rename = "sv")]
    Sv,
    #[serde(rename = "tr")]
    Tr,
    #[serde(rename = "zh_CN")]
    ZhCn,
    #[serde(rename = "zh_TW")]
    ZhTw,

}

impl std::fmt::Display for PdmDefaultLangEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ar => write!(f, "ar"),
            Self::Ca => write!(f, "ca"),
            Self::Da => write!(f, "da"),
            Self::De => write!(f, "de"),
            Self::En => write!(f, "en"),
            Self::Es => write!(f, "es"),
            Self::Eu => write!(f, "eu"),
            Self::Fa => write!(f, "fa"),
            Self::Fr => write!(f, "fr"),
            Self::Gl => write!(f, "gl"),
            Self::He => write!(f, "he"),
            Self::Hu => write!(f, "hu"),
            Self::It => write!(f, "it"),
            Self::Ja => write!(f, "ja"),
            Self::Kr => write!(f, "kr"),
            Self::Nb => write!(f, "nb"),
            Self::Nl => write!(f, "nl"),
            Self::Nn => write!(f, "nn"),
            Self::Pl => write!(f, "pl"),
            Self::PtBr => write!(f, "pt_BR"),
            Self::Ru => write!(f, "ru"),
            Self::Sl => write!(f, "sl"),
            Self::Sv => write!(f, "sv"),
            Self::Tr => write!(f, "tr"),
            Self::ZhCn => write!(f, "zh_CN"),
            Self::ZhTw => write!(f, "zh_TW"),
        }
    }
}

impl Default for PdmDefaultLangEnum {
    fn default() -> PdmDefaultLangEnum {
        Self::Ar
    }
}

