/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmResourcesStateEnum {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "mixed")]
    Mixed,
    #[serde(rename = "active")]
    Active,

}

impl std::fmt::Display for PdmResourcesStateEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Unknown => write!(f, "unknown"),
            Self::Mixed => write!(f, "mixed"),
            Self::Active => write!(f, "active"),
        }
    }
}

impl Default for PdmResourcesStateEnum {
    fn default() -> PdmResourcesStateEnum {
        Self::None
    }
}

