/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmSdnZonesTyEnum {
    #[serde(rename = "evpn")]
    Evpn,
    #[serde(rename = "faucet")]
    Faucet,
    #[serde(rename = "qinq")]
    Qinq,
    #[serde(rename = "simple")]
    Simple,
    #[serde(rename = "vlan")]
    Vlan,
    #[serde(rename = "vxlan")]
    Vxlan,

}

impl std::fmt::Display for PdmSdnZonesTyEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Evpn => write!(f, "evpn"),
            Self::Faucet => write!(f, "faucet"),
            Self::Qinq => write!(f, "qinq"),
            Self::Simple => write!(f, "simple"),
            Self::Vlan => write!(f, "vlan"),
            Self::Vxlan => write!(f, "vxlan"),
        }
    }
}

impl Default for PdmSdnZonesTyEnum {
    fn default() -> PdmSdnZonesTyEnum {
        Self::Evpn
    }
}

