/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmPveRemotesLockEnum2 {
    #[serde(rename = "backup")]
    Backup,
    #[serde(rename = "clone")]
    Clone,
    #[serde(rename = "create")]
    Create,
    #[serde(rename = "migrate")]
    Migrate,
    #[serde(rename = "rollback")]
    Rollback,
    #[serde(rename = "snapshot")]
    Snapshot,
    #[serde(rename = "snapshot-delete")]
    SnapshotDelete,
    #[serde(rename = "suspending")]
    Suspending,
    #[serde(rename = "suspended")]
    Suspended,

}

impl std::fmt::Display for PdmPveRemotesLockEnum2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Backup => write!(f, "backup"),
            Self::Clone => write!(f, "clone"),
            Self::Create => write!(f, "create"),
            Self::Migrate => write!(f, "migrate"),
            Self::Rollback => write!(f, "rollback"),
            Self::Snapshot => write!(f, "snapshot"),
            Self::SnapshotDelete => write!(f, "snapshot-delete"),
            Self::Suspending => write!(f, "suspending"),
            Self::Suspended => write!(f, "suspended"),
        }
    }
}

impl Default for PdmPveRemotesLockEnum2 {
    fn default() -> PdmPveRemotesLockEnum2 {
        Self::Backup
    }
}

