/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PdmError : Proxmox Datacenter Manager error envelope. Returned for all 4xx/5xx responses. `message` is always populated; `errors` is populated for validation failures with one entry per offending parameter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdmError {

    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<serde_json::Value>>,

    #[serde(rename = "message")]
    pub message: String,

    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<std::collections::HashMap<String, String>>,


}

impl PdmError {
    /// Proxmox Datacenter Manager error envelope. Returned for all 4xx/5xx responses. `message` is always populated; `errors` is populated for validation failures with one entry per offending parameter.
    pub fn new(message: String) -> PdmError {
        PdmError {
            
            data: None,
            
            message,
            
            errors: None,
            
        }
    }
}


