/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdmRemoveVanishedConfig {

    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<serde_json::Value>,

    /// remove-vanished options
    #[serde(rename = "items")]
    pub items: models::PdmAccessDomainsItemsEnum,

    #[serde(rename = "maxLength", deserialize_with = "Option::deserialize")]
    pub max_length: Option<serde_json::Value>,

    #[serde(rename = "minLength", deserialize_with = "Option::deserialize")]
    pub min_length: Option<serde_json::Value>,

    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,


}

impl PdmRemoveVanishedConfig {
    pub fn new(description: Option<serde_json::Value>, items: models::PdmAccessDomainsItemsEnum, max_length: Option<serde_json::Value>, min_length: Option<serde_json::Value>, r#type: Option<serde_json::Value>) -> PdmRemoveVanishedConfig {
        PdmRemoveVanishedConfig {
            
            description,
            
            items,
            
            max_length,
            
            min_length,
            
            r#type,
            
        }
    }
}


