/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmConfigAccessInlineEnum {
    #[serde(rename = "client-key")]
    ClientKey,
    #[serde(rename = "comment")]
    Comment,
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "autocreate")]
    Autocreate,
    #[serde(rename = "scopes")]
    Scopes,
    #[serde(rename = "prompt")]
    Prompt,
    #[serde(rename = "acr-values")]
    AcrValues,

}

impl std::fmt::Display for PdmConfigAccessInlineEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClientKey => write!(f, "client-key"),
            Self::Comment => write!(f, "comment"),
            Self::Default => write!(f, "default"),
            Self::Autocreate => write!(f, "autocreate"),
            Self::Scopes => write!(f, "scopes"),
            Self::Prompt => write!(f, "prompt"),
            Self::AcrValues => write!(f, "acr-values"),
        }
    }
}

impl Default for PdmConfigAccessInlineEnum {
    fn default() -> PdmConfigAccessInlineEnum {
        Self::ClientKey
    }
}

