/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmNodesNetworkTypeEnum {
    #[serde(rename = "loopback")]
    Loopback,
    #[serde(rename = "eth")]
    Eth,
    #[serde(rename = "bridge")]
    Bridge,
    #[serde(rename = "bond")]
    Bond,
    #[serde(rename = "vlan")]
    Vlan,
    #[serde(rename = "alias")]
    Alias,
    #[serde(rename = "unknown")]
    Unknown,

}

impl std::fmt::Display for PdmNodesNetworkTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Loopback => write!(f, "loopback"),
            Self::Eth => write!(f, "eth"),
            Self::Bridge => write!(f, "bridge"),
            Self::Bond => write!(f, "bond"),
            Self::Vlan => write!(f, "vlan"),
            Self::Alias => write!(f, "alias"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

impl Default for PdmNodesNetworkTypeEnum {
    fn default() -> PdmNodesNetworkTypeEnum {
        Self::Loopback
    }
}

