/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmCfEnum {
    #[serde(rename = "MAX")]
    Max,
    #[serde(rename = "AVERAGE")]
    Average,

}

impl std::fmt::Display for PdmCfEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Max => write!(f, "MAX"),
            Self::Average => write!(f, "AVERAGE"),
        }
    }
}

impl Default for PdmCfEnum {
    fn default() -> PdmCfEnum {
        Self::Max
    }
}

