/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PdmItemsEnum {
    #[serde(rename = "amanda")]
    Amanda,
    #[serde(rename = "ftp")]
    Ftp,
    #[serde(rename = "irc")]
    Irc,
    #[serde(rename = "netbios-ns")]
    NetbiosNs,
    #[serde(rename = "pptp")]
    Pptp,
    #[serde(rename = "sane")]
    Sane,
    #[serde(rename = "sip")]
    Sip,
    #[serde(rename = "snmp")]
    Snmp,
    #[serde(rename = "tftp")]
    Tftp,

}

impl std::fmt::Display for PdmItemsEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Amanda => write!(f, "amanda"),
            Self::Ftp => write!(f, "ftp"),
            Self::Irc => write!(f, "irc"),
            Self::NetbiosNs => write!(f, "netbios-ns"),
            Self::Pptp => write!(f, "pptp"),
            Self::Sane => write!(f, "sane"),
            Self::Sip => write!(f, "sip"),
            Self::Snmp => write!(f, "snmp"),
            Self::Tftp => write!(f, "tftp"),
        }
    }
}

impl Default for PdmItemsEnum {
    fn default() -> PdmItemsEnum {
        Self::Amanda
    }
}

