/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesCreateRemoteMigrateRequest {

    /// Override I/O bandwidth limit (in KiB/s).
    #[serde(rename = "bwlimit", skip_serializing_if = "Option::is_none")]
    pub bwlimit: Option<i64>,

    /// Delete the original VM and related data after successful migration.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,

    /// Node name (or 'localhost')
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,

    /// Perform an online migration if the vm is running.
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<bool>,

    /// Perform a restart-migration.
    #[serde(rename = "restart", skip_serializing_if = "Option::is_none")]
    pub restart: Option<bool>,

    /// Remote ID.
    #[serde(rename = "target")]
    pub target: String,

    /// List of bridge mappings
    #[serde(rename = "target-bridge")]
    pub target_bridge: Vec<String>,

    /// The target endpoint to use for the connection.
    #[serde(rename = "target-endpoint", skip_serializing_if = "Option::is_none")]
    pub target_endpoint: Option<String>,

    /// List of storage mappings
    #[serde(rename = "target-storage")]
    pub target_storage: Vec<String>,

    /// A guest ID
    #[serde(rename = "target-vmid", skip_serializing_if = "Option::is_none")]
    pub target_vmid: Option<i64>,

    /// Add a shutdown timeout for the restart-migration.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,


}

impl PveRemotesCreateRemoteMigrateRequest {
    pub fn new(target: String, target_bridge: Vec<String>, target_storage: Vec<String>) -> PveRemotesCreateRemoteMigrateRequest {
        PveRemotesCreateRemoteMigrateRequest {
            
            bwlimit: None,
            
            delete: None,
            
            node: None,
            
            online: None,
            
            restart: None,
            
            target,
            
            target_bridge,
            
            target_endpoint: None,
            
            target_storage,
            
            target_vmid: None,
            
            timeout: None,
            
        }
    }
}


