/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesUpdateOptionsRequest {

    /// A list of settings you want to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<String>>,

    /// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Enable ebtables rules cluster wide.
    #[serde(rename = "ebtables", skip_serializing_if = "Option::is_none")]
    pub ebtables: Option<bool>,

    /// Enable or disable the firewall cluster wide.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<i64>,

    /// Log ratelimiting settings
    #[serde(rename = "log_ratelimit", skip_serializing_if = "Option::is_none")]
    pub log_ratelimit: Option<Box<models::PdmLogRatelimitField>>,

    /// Firewall IO policies.
    #[serde(rename = "policy_forward", skip_serializing_if = "Option::is_none")]
    pub policy_forward: Option<models::PdmPolicyForwardEnum>,

    /// Firewall IO policies.
    #[serde(rename = "policy_in", skip_serializing_if = "Option::is_none")]
    pub policy_in: Option<models::PdmPolicyInEnum>,

    /// Firewall IO policies.
    #[serde(rename = "policy_out", skip_serializing_if = "Option::is_none")]
    pub policy_out: Option<models::PdmPolicyInEnum>,


}

impl PveRemotesUpdateOptionsRequest {
    pub fn new() -> PveRemotesUpdateOptionsRequest {
        PveRemotesUpdateOptionsRequest {
            
            delete: None,
            
            digest: None,
            
            ebtables: None,
            
            enable: None,
            
            log_ratelimit: None,
            
            policy_forward: None,
            
            policy_in: None,
            
            policy_out: None,
            
        }
    }
}


