/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesCreatePveRemotesByRemoteQemuByVmidMigrateRequest {

    /// Override I/O bandwidth limit (in KiB/s).
    #[serde(rename = "bwlimit", skip_serializing_if = "Option::is_none")]
    pub bwlimit: Option<i64>,

    /// Allow to migrate VMs with local devices.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,

    /// CIDR of the (sub) network that is used for migration.
    #[serde(rename = "migration-network", skip_serializing_if = "Option::is_none")]
    pub migration_network: Option<String>,

    /// Migration traffic is encrypted using an SSH tunnel by default. On secure, completely private networks this can be disabled to increase performance.
    #[serde(rename = "migration-type", skip_serializing_if = "Option::is_none")]
    pub migration_type: Option<models::PdmPveRemotesMigrationTypeEnum>,

    /// Node name (or 'localhost')
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,

    /// Perform an online migration if the vm is running.
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<bool>,

    /// Node name (or 'localhost')
    #[serde(rename = "target")]
    pub target: String,

    /// List of storage mappings
    #[serde(rename = "target-storage", skip_serializing_if = "Option::is_none")]
    pub target_storage: Option<Vec<String>>,

    /// Enable live storage migration for local disks.
    #[serde(rename = "with-local-disks", skip_serializing_if = "Option::is_none")]
    pub with_local_disks: Option<bool>,


}

impl PveRemotesCreatePveRemotesByRemoteQemuByVmidMigrateRequest {
    pub fn new(target: String) -> PveRemotesCreatePveRemotesByRemoteQemuByVmidMigrateRequest {
        PveRemotesCreatePveRemotesByRemoteQemuByVmidMigrateRequest {
            
            bwlimit: None,
            
            force: None,
            
            migration_network: None,
            
            migration_type: None,
            
            node: None,
            
            online: None,
            
            target,
            
            target_storage: None,
            
            with_local_disks: None,
            
        }
    }
}


