/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataCurrentKernel : Meta-information about the currently booted kernel of this node.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataCurrentKernel {

    /// Hardware (architecture) type
    #[serde(rename = "machine")]
    pub machine: String,

    /// OS kernel release (e.g., \"6.8.0\")
    #[serde(rename = "release")]
    pub release: String,

    /// OS kernel name (e.g., \"Linux\")
    #[serde(rename = "sysname")]
    pub sysname: String,

    /// OS kernel version with build info
    #[serde(rename = "version")]
    pub version: String,


}

impl PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataCurrentKernel {
    /// Meta-information about the currently booted kernel of this node.
    pub fn new(machine: String, release: String, sysname: String, version: String) -> PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataCurrentKernel {
        PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataCurrentKernel {
            
            machine,
            
            release,
            
            sysname,
            
            version,
            
        }
    }
}


