/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetNodesResponseDataInner {

    /// CPU utilization.
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<f64>,

    /// Support level.
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<String>,

    /// Number of available CPUs.
    #[serde(rename = "maxcpu", skip_serializing_if = "Option::is_none")]
    pub maxcpu: Option<i64>,

    /// Number of available memory in bytes.
    #[serde(rename = "maxmem", skip_serializing_if = "Option::is_none")]
    pub maxmem: Option<i64>,

    /// Used memory in bytes.
    #[serde(rename = "mem", skip_serializing_if = "Option::is_none")]
    pub mem: Option<i64>,

    /// The cluster node name.
    #[serde(rename = "node")]
    pub node: String,

    /// The SSL fingerprint for the node certificate.
    #[serde(rename = "ssl_fingerprint", skip_serializing_if = "Option::is_none")]
    pub ssl_fingerprint: Option<String>,

    /// Node status.
    #[serde(rename = "status")]
    pub status: models::PdmPveRemotesStatusEnum,

    /// Node uptime in seconds.
    #[serde(rename = "uptime", skip_serializing_if = "Option::is_none")]
    pub uptime: Option<i64>,


}

impl PveRemotesGetNodesResponseDataInner {
    pub fn new(node: String, status: models::PdmPveRemotesStatusEnum) -> PveRemotesGetNodesResponseDataInner {
        PveRemotesGetNodesResponseDataInner {
            
            cpu: None,
            
            level: None,
            
            maxcpu: None,
            
            maxmem: None,
            
            mem: None,
            
            node,
            
            ssl_fingerprint: None,
            
            status,
            
            uptime: None,
            
        }
    }
}


