/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetMigrateResponseDataNotAllowedNodesBlockingHaResourcesInner {

    /// The reason why the HA resource is blocking the migration.
    #[serde(rename = "cause")]
    pub cause: models::PdmPveRemotesCauseEnum,

    /// The blocking HA resource id
    #[serde(rename = "sid")]
    pub sid: String,


}

impl PveRemotesGetMigrateResponseDataNotAllowedNodesBlockingHaResourcesInner {
    pub fn new(cause: models::PdmPveRemotesCauseEnum, sid: String) -> PveRemotesGetMigrateResponseDataNotAllowedNodesBlockingHaResourcesInner {
        PveRemotesGetMigrateResponseDataNotAllowedNodesBlockingHaResourcesInner {
            
            cause,
            
            sid,
            
        }
    }
}


