/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageRrddataResponseDataInner {

    /// Total disk size
    #[serde(rename = "disk-total", skip_serializing_if = "Option::is_none")]
    pub disk_total: Option<f64>,

    /// Disk utiliziation
    #[serde(rename = "disk-used", skip_serializing_if = "Option::is_none")]
    pub disk_used: Option<f64>,

    /// Timestamp (UNIX epoch)
    #[serde(rename = "time")]
    pub time: i64,


}

impl PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageRrddataResponseDataInner {
    pub fn new(time: i64) -> PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageRrddataResponseDataInner {
        PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageRrddataResponseDataInner {
            
            disk_total: None,
            
            disk_used: None,
            
            time,
            
        }
    }
}


