/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetMigrateResponseDataLocalDisksInner {

    /// True if the disk is a cdrom.
    #[serde(rename = "cdrom")]
    pub cdrom: bool,

    /// True if the disk is unused.
    #[serde(rename = "is_unused")]
    pub is_unused: bool,

    /// The size of the disk in bytes.
    #[serde(rename = "size")]
    pub size: i64,

    /// The volid of the disk.
    #[serde(rename = "volid")]
    pub volid: String,


}

impl PveRemotesGetMigrateResponseDataLocalDisksInner {
    pub fn new(cdrom: bool, is_unused: bool, size: i64, volid: String) -> PveRemotesGetMigrateResponseDataLocalDisksInner {
        PveRemotesGetMigrateResponseDataLocalDisksInner {
            
            cdrom,
            
            is_unused,
            
            size,
            
            volid,
            
        }
    }
}


