/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveFirewallGetStatusResponseDataInnerNodesInnerGuestsInner {

    /// The type of the guest
    #[serde(rename = "kind")]
    pub kind: models::PdmKindEnum,

    /// Name of the guest.
    #[serde(rename = "name")]
    pub name: String,

    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<models::PveFirewallGetStatusResponseDataInnerNodesInnerGuestsInnerStatus>>,

    /// A guest ID
    #[serde(rename = "vmid")]
    pub vmid: i64,


}

impl PveFirewallGetStatusResponseDataInnerNodesInnerGuestsInner {
    pub fn new(kind: models::PdmKindEnum, name: String, vmid: i64) -> PveFirewallGetStatusResponseDataInnerNodesInnerGuestsInner {
        PveFirewallGetStatusResponseDataInnerNodesInnerGuestsInner {
            
            kind,
            
            name,
            
            status: None,
            
            vmid,
            
        }
    }
}


