/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesCreateMigrateRequest {

    /// Override I/O bandwidth limit (in KiB/s).
    #[serde(rename = "bwlimit", skip_serializing_if = "Option::is_none")]
    pub bwlimit: Option<i64>,

    /// Node name (or 'localhost')
    #[serde(rename = "node", skip_serializing_if = "Option::is_none")]
    pub node: Option<String>,

    /// Attempt an online migration if the container is running.
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<bool>,

    /// Perform a restart-migration if the container is running.
    #[serde(rename = "restart", skip_serializing_if = "Option::is_none")]
    pub restart: Option<bool>,

    /// Node name (or 'localhost')
    #[serde(rename = "target")]
    pub target: String,

    /// List of storage mappings
    #[serde(rename = "target-storage", skip_serializing_if = "Option::is_none")]
    pub target_storage: Option<Vec<String>>,

    /// Shutdown timeout for restart-migrations.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,


}

impl PveRemotesCreateMigrateRequest {
    pub fn new(target: String) -> PveRemotesCreateMigrateRequest {
        PveRemotesCreateMigrateRequest {
            
            bwlimit: None,
            
            node: None,
            
            online: None,
            
            restart: None,
            
            target,
            
            target_storage: None,
            
            timeout: None,
            
        }
    }
}


