/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetTasksResponseDataInner {

    /// The task's end time.
    #[serde(rename = "endtime", skip_serializing_if = "Option::is_none")]
    pub endtime: Option<i64>,

    /// The task id.
    #[serde(rename = "id")]
    pub id: String,

    /// The task's node.
    #[serde(rename = "node")]
    pub node: String,

    /// The task process id.
    #[serde(rename = "pid")]
    pub pid: i64,

    /// The task's proc start time.
    #[serde(rename = "pstart")]
    pub pstart: i64,

    /// The task's start time.
    #[serde(rename = "starttime")]
    pub starttime: i64,

    /// The task's status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,

    /// The task type.
    #[serde(rename = "type")]
    pub r#type: String,

    /// The task's UPID.
    #[serde(rename = "upid")]
    pub upid: String,

    /// The task owner's user id.
    #[serde(rename = "user")]
    pub user: String,


}

impl PveRemotesGetTasksResponseDataInner {
    pub fn new(id: String, node: String, pid: i64, pstart: i64, starttime: i64, r#type: String, upid: String, user: String) -> PveRemotesGetTasksResponseDataInner {
        PveRemotesGetTasksResponseDataInner {
            
            endtime: None,
            
            id,
            
            node,
            
            pid,
            
            pstart,
            
            starttime,
            
            status: None,
            
            r#type,
            
            upid,
            
            user,
            
        }
    }
}


