/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataRootfs : Object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataRootfs {

    /// The available bytes in the root filesystem.
    #[serde(rename = "avail")]
    pub avail: i64,

    /// The free bytes on the root filesystem.
    #[serde(rename = "free")]
    pub free: i64,

    /// The total size of the root filesystem in bytes.
    #[serde(rename = "total")]
    pub total: i64,

    /// The used bytes in the root filesystem.
    #[serde(rename = "used")]
    pub used: i64,


}

impl PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataRootfs {
    /// Object.
    pub fn new(avail: i64, free: i64, total: i64, used: i64) -> PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataRootfs {
        PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataRootfs {
            
            avail,
            
            free,
            
            total,
            
            used,
            
        }
    }
}


