/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataBootInfo : Meta-information about the boot mode.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataBootInfo {

    /// Through which firmware the system got booted.
    #[serde(rename = "mode")]
    pub mode: models::PdmNodesStatusModeEnum,

    /// System is booted in secure mode, only applicable for the \"efi\" mode.
    #[serde(rename = "secureboot", skip_serializing_if = "Option::is_none")]
    pub secureboot: Option<bool>,


}

impl PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataBootInfo {
    /// Meta-information about the boot mode.
    pub fn new(mode: models::PdmNodesStatusModeEnum) -> PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataBootInfo {
        PveRemotesGetPveRemotesByRemoteNodesByNodeStatusResponseDataBootInfo {
            
            mode,
            
            secureboot: None,
            
        }
    }
}


