/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesUpdatePveRemotesByRemoteNodesByNodeFirewallOptionsRequest {

    /// A list of settings you want to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<Vec<String>>,

    /// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Enable host firewall rules.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,

    /// Firewall log levels.
    #[serde(rename = "log_level_forward", skip_serializing_if = "Option::is_none")]
    pub log_level_forward: Option<models::PdmLogLevelInEnum>,

    /// Firewall log levels.
    #[serde(rename = "log_level_in", skip_serializing_if = "Option::is_none")]
    pub log_level_in: Option<models::PdmLogLevelInEnum>,

    /// Firewall log levels.
    #[serde(rename = "log_level_out", skip_serializing_if = "Option::is_none")]
    pub log_level_out: Option<models::PdmLogLevelInEnum>,

    /// Enable logging of conntrack information.
    #[serde(rename = "log_nf_conntrack", skip_serializing_if = "Option::is_none")]
    pub log_nf_conntrack: Option<bool>,

    /// Enable NDP (Neighbor Discovery Protocol).
    #[serde(rename = "ndp", skip_serializing_if = "Option::is_none")]
    pub ndp: Option<bool>,

    /// Allow invalid packets on connection tracking.
    #[serde(rename = "nf_conntrack_allow_invalid", skip_serializing_if = "Option::is_none")]
    pub nf_conntrack_allow_invalid: Option<bool>,

    /// Enable conntrack helpers for specific protocols. Supported protocols: amanda, ftp, irc, netbios-ns, pptp, sane, sip, snmp, tftp
    #[serde(rename = "nf_conntrack_helpers", skip_serializing_if = "Option::is_none")]
    pub nf_conntrack_helpers: Option<Box<models::PdmNfConntrackHelpersField>>,

    /// Maximum number of tracked connections.
    #[serde(rename = "nf_conntrack_max", skip_serializing_if = "Option::is_none")]
    pub nf_conntrack_max: Option<i64>,

    /// Conntrack established timeout.
    #[serde(rename = "nf_conntrack_tcp_timeout_established", skip_serializing_if = "Option::is_none")]
    pub nf_conntrack_tcp_timeout_established: Option<i64>,

    /// Conntrack syn recv timeout.
    #[serde(rename = "nf_conntrack_tcp_timeout_syn_recv", skip_serializing_if = "Option::is_none")]
    pub nf_conntrack_tcp_timeout_syn_recv: Option<i32>,

    /// Enable nftables based firewall (tech preview)
    #[serde(rename = "nftables", skip_serializing_if = "Option::is_none")]
    pub nftables: Option<bool>,

    /// Enable SMURFS filter.
    #[serde(rename = "nosmurfs", skip_serializing_if = "Option::is_none")]
    pub nosmurfs: Option<bool>,

    /// Enable synflood protection
    #[serde(rename = "protection_synflood", skip_serializing_if = "Option::is_none")]
    pub protection_synflood: Option<bool>,

    /// Synflood protection rate burst by ip src.
    #[serde(rename = "protection_synflood_burst", skip_serializing_if = "Option::is_none")]
    pub protection_synflood_burst: Option<i64>,

    /// Synflood protection rate syn/sec by ip src.
    #[serde(rename = "protection_synflood_rate", skip_serializing_if = "Option::is_none")]
    pub protection_synflood_rate: Option<i64>,

    /// Firewall log levels.
    #[serde(rename = "smurf_log_level", skip_serializing_if = "Option::is_none")]
    pub smurf_log_level: Option<models::PdmLogLevelInEnum>,

    /// Firewall log levels.
    #[serde(rename = "tcp_flags_log_level", skip_serializing_if = "Option::is_none")]
    pub tcp_flags_log_level: Option<models::PdmLogLevelInEnum>,

    /// Filter illegal combinations of TCP flags.
    #[serde(rename = "tcpflags", skip_serializing_if = "Option::is_none")]
    pub tcpflags: Option<bool>,


}

impl PveRemotesUpdatePveRemotesByRemoteNodesByNodeFirewallOptionsRequest {
    pub fn new() -> PveRemotesUpdatePveRemotesByRemoteNodesByNodeFirewallOptionsRequest {
        PveRemotesUpdatePveRemotesByRemoteNodesByNodeFirewallOptionsRequest {
            
            delete: None,
            
            digest: None,
            
            enable: None,
            
            log_level_forward: None,
            
            log_level_in: None,
            
            log_level_out: None,
            
            log_nf_conntrack: None,
            
            ndp: None,
            
            nf_conntrack_allow_invalid: None,
            
            nf_conntrack_helpers: None,
            
            nf_conntrack_max: None,
            
            nf_conntrack_tcp_timeout_established: None,
            
            nf_conntrack_tcp_timeout_syn_recv: None,
            
            nftables: None,
            
            nosmurfs: None,
            
            protection_synflood: None,
            
            protection_synflood_burst: None,
            
            protection_synflood_rate: None,
            
            smurf_log_level: None,
            
            tcp_flags_log_level: None,
            
            tcpflags: None,
            
        }
    }
}


