/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageStatusResponseData {

    /// Set when storage is accessible.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,

    /// Available storage space in bytes.
    #[serde(rename = "avail", skip_serializing_if = "Option::is_none")]
    pub avail: Option<i64>,

    /// Allowed storage content types.
    #[serde(rename = "content")]
    pub content: Box<models::PdmContentField>,

    /// Set when storage is enabled (not disabled).
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,

    /// Shared flag from storage configuration.
    #[serde(rename = "shared", skip_serializing_if = "Option::is_none")]
    pub shared: Option<bool>,

    /// Total storage space in bytes.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,

    /// Storage type.
    #[serde(rename = "type")]
    pub r#type: String,

    /// Used storage space in bytes.
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<i64>,


}

impl PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageStatusResponseData {
    pub fn new(content: models::PdmContentField, r#type: String) -> PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageStatusResponseData {
        PveRemotesGetPveRemotesByRemoteNodesByNodeStorageByStorageStatusResponseData {
            
            active: None,
            
            avail: None,
            
            content: Box::new(content),
            
            enabled: None,
            
            shared: None,
            
            total: None,
            
            r#type,
            
            used: None,
            
        }
    }
}


