/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemotesTasksGetStatisticsResponseData {

    /// A map of remotes to status counts
    #[serde(rename = "by-remote")]
    pub by_remote: serde_json::Value,

    /// A map of worker-types to status counts
    #[serde(rename = "by-type")]
    pub by_type: serde_json::Value,


}

impl RemotesTasksGetStatisticsResponseData {
    pub fn new(by_remote: serde_json::Value, by_type: serde_json::Value) -> RemotesTasksGetStatisticsResponseData {
        RemotesTasksGetStatisticsResponseData {
            
            by_remote,
            
            by_type,
            
        }
    }
}


