/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemotesRemoteGetVersionResponseData {

    /// The default console viewer to use.
    #[serde(rename = "console", skip_serializing_if = "Option::is_none")]
    pub console: Option<models::PdmRemotesRemoteConsoleEnum>,

    /// The current Proxmox VE point release in `x.y` format.
    #[serde(rename = "release")]
    pub release: String,

    /// The short git revision from which this version was build.
    #[serde(rename = "repoid")]
    pub repoid: String,

    /// The full pve-manager package version of this node.
    #[serde(rename = "version")]
    pub version: String,


}

impl RemotesRemoteGetVersionResponseData {
    pub fn new(release: String, repoid: String, version: String) -> RemotesRemoteGetVersionResponseData {
        RemotesRemoteGetVersionResponseData {
            
            console: None,
            
            release,
            
            repoid,
            
            version,
            
        }
    }
}


