/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemotesRemoteCreateRemoteRequest {

    /// Authentication ID
    #[serde(rename = "authid")]
    pub authid: String,

    /// If given, create this token on the remote and use it.
    #[serde(rename = "create-token", skip_serializing_if = "Option::is_none")]
    pub create_token: Option<String>,

    /// Remote ID.
    #[serde(rename = "id")]
    pub id: String,

    /// A list of cluster node addresses.
    #[serde(rename = "nodes")]
    pub nodes: Vec<String>,

    /// The access token's secret.
    #[serde(rename = "token")]
    pub token: String,

    /// The type of a remote entry.
    #[serde(rename = "type")]
    pub r#type: models::PdmPbsTypeEnum,

    /// Configuration for the Web UI URL link generation.
    #[serde(rename = "web-url", skip_serializing_if = "Option::is_none")]
    pub web_url: Option<String>,


}

impl RemotesRemoteCreateRemoteRequest {
    pub fn new(authid: String, id: String, nodes: Vec<String>, token: String, r#type: models::PdmPbsTypeEnum) -> RemotesRemoteCreateRemoteRequest {
        RemotesRemoteCreateRemoteRequest {
            
            authid,
            
            create_token: None,
            
            id,
            
            nodes,
            
            token,
            
            r#type,
            
            web_url: None,
            
        }
    }
}


