/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemotesMetricCollectionGetStatusResponseDataInner {

    /// Any error that occured during the last collection attempt.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,

    /// Timestamp of last successful collection.
    #[serde(rename = "last-collection", skip_serializing_if = "Option::is_none")]
    pub last_collection: Option<i64>,

    /// The remote's name.
    #[serde(rename = "remote")]
    pub remote: String,


}

impl RemotesMetricCollectionGetStatusResponseDataInner {
    pub fn new(remote: String) -> RemotesMetricCollectionGetStatusResponseDataInner {
        RemotesMetricCollectionGetStatusResponseDataInner {
            
            error: None,
            
            last_collection: None,
            
            remote,
            
        }
    }
}


