/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemotesUpdatesGetSummaryResponseData {

    /// Map of per-remote update summaries
    #[serde(rename = "remotes")]
    pub remotes: serde_json::Value,


}

impl RemotesUpdatesGetSummaryResponseData {
    pub fn new(remotes: serde_json::Value) -> RemotesUpdatesGetSummaryResponseData {
        RemotesUpdatesGetSummaryResponseData {
            
            remotes,
            
        }
    }
}


