/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourcesGetSubscriptionResponseDataInner {

    /// Any error that occurred when querying remote resources
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,

    /// A map from nodename to subscription info
    #[serde(rename = "node-status", skip_serializing_if = "Option::is_none")]
    pub node_status: Option<serde_json::Value>,

    /// Remote name
    #[serde(rename = "remote")]
    pub remote: String,

    /// Describes the state of subscription of the remote
    #[serde(rename = "state")]
    pub state: models::PdmResourcesStateEnum,


}

impl ResourcesGetSubscriptionResponseDataInner {
    pub fn new(remote: String, state: models::PdmResourcesStateEnum) -> ResourcesGetSubscriptionResponseDataInner {
        ResourcesGetSubscriptionResponseDataInner {
            
            error: None,
            
            node_status: None,
            
            remote,
            
            state,
            
        }
    }
}


