/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourcesGetTopEntitiesResponseDataGuestCpuInner {

    /// The remote the resource is on
    #[serde(rename = "remote")]
    pub remote: String,

    #[serde(rename = "resource")]
    pub resource: serde_json::Value,

    #[serde(rename = "rrd-data")]
    pub rrd_data: Box<models::ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData>,


}

impl ResourcesGetTopEntitiesResponseDataGuestCpuInner {
    pub fn new(remote: String, resource: serde_json::Value, rrd_data: models::ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData) -> ResourcesGetTopEntitiesResponseDataGuestCpuInner {
        ResourcesGetTopEntitiesResponseDataGuestCpuInner {
            
            remote,
            
            resource,
            
            rrd_data: Box::new(rrd_data),
            
        }
    }
}


