/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SdnZonesCreateZonesRequestRemotesInner {

    /// The name for an SDN controller.
    #[serde(rename = "controller")]
    pub controller: String,

    /// Remote ID.
    #[serde(rename = "remote")]
    pub remote: String,


}

impl SdnZonesCreateZonesRequestRemotesInner {
    pub fn new(controller: String, remote: String) -> SdnZonesCreateZonesRequestRemotesInner {
        SdnZonesCreateZonesRequestRemotesInner {
            
            controller,
            
            remote,
            
        }
    }
}


