/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SdnVnetsGetVnetsResponseDataInner {

    /// Alias name of the VNet.
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,

    /// Digest of the VNet section.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// If true, sets the isolated property for all interfaces on the bridge of this VNet.
    #[serde(rename = "isolate-ports", skip_serializing_if = "Option::is_none")]
    pub isolate_ports: Option<bool>,

    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<Box<models::SdnVnetsGetVnetsResponseDataInnerPending>>,

    /// Remote ID.
    #[serde(rename = "remote")]
    pub remote: String,

    /// The state of an SDN object.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<models::PdmSdnStateEnum>,

    /// VLAN Tag (for VLAN or QinQ zones) or VXLAN VNI (for VXLAN or EVPN zones).
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<i32>,

    /// Type of the VNet.
    #[serde(rename = "type")]
    pub r#type: models::PdmSdnVnetsTypeEnum,

    /// Allow VLANs to pass through this VNet.
    #[serde(rename = "vlanaware", skip_serializing_if = "Option::is_none")]
    pub vlanaware: Option<bool>,

    /// Name of the VNet.
    #[serde(rename = "vnet")]
    pub vnet: String,

    /// Name of the zone this VNet belongs to.
    #[serde(rename = "zone", skip_serializing_if = "Option::is_none")]
    pub zone: Option<String>,


}

impl SdnVnetsGetVnetsResponseDataInner {
    pub fn new(remote: String, r#type: models::PdmSdnVnetsTypeEnum, vnet: String) -> SdnVnetsGetVnetsResponseDataInner {
        SdnVnetsGetVnetsResponseDataInner {
            
            alias: None,
            
            digest: None,
            
            isolate_ports: None,
            
            pending: None,
            
            remote,
            
            state: None,
            
            tag: None,
            
            r#type,
            
            vlanaware: None,
            
            vnet,
            
            zone: None,
            
        }
    }
}


