/*
 * Proxmox Datacenter Manager API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SdnVnetsCreateVnetsRequest {

    /// List of remotes with the zone in which the VNet should get created.
    #[serde(rename = "remotes")]
    pub remotes: Vec<models::SdnVnetsCreateVnetsRequestRemotesInner>,

    /// VXLAN VNI
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<i32>,

    /// The name for an SDN object (zone / vnet / fabric).
    #[serde(rename = "vnet")]
    pub vnet: String,


}

impl SdnVnetsCreateVnetsRequest {
    pub fn new(remotes: Vec<models::SdnVnetsCreateVnetsRequestRemotesInner>, vnet: String) -> SdnVnetsCreateVnetsRequest {
        SdnVnetsCreateVnetsRequest {
            
            remotes,
            
            tag: None,
            
            vnet,
            
        }
    }
}


